Repository sunpy/sunpy, pull requests merged in 2018-04, with the labels that each got.

#2577 fix failing doctest
  docs/guide/acquiring_data/jsoc.rst
Labels: Merge When CI Passes, [DocFix]

#2480 Set assumed coordinates in mapbase
  CHANGELOG.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: coordinates

#2437 Add HEEQ coordinate frame
  CHANGELOG.rst
  sunpy/coordinates/frames.py
  sunpy/coordinates/tests/test_frames.py
  sunpy/coordinates/tests/test_transformations.py
Labels: coordinates

#2586 Fix #2585 update package name in setup.py
  setup.py
Labels: 0.8.x, Affects Release, Priority High

#2589 Fix bs4 UserWarnings
  sunpy/net/helio/parser.py
  sunpy/spectra/sources/callisto.py
  sunpy/util/scraper.py
Labels: 0.8.x, Affects Release, [BugFix], net

#2587 Minor CI fix
  .travis.yml
  docs/conf.py
  docs/guide/acquiring_data/jsoc.rst
  requirements/base.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/extra.txt
  requirements/rtd.txt
  setup.py
  sunpy/net/jsoc/jsoc.py
Labels: Merge When CI Passes

#2592 Doc fixes
  docs/guide/acquiring_data/jsoc.rst
  sunpy/net/jsoc/attrs.py
  sunpy/net/jsoc/jsoc.py
Labels: Affects Dev, Merge When CI Passes, [DocFix]

#2595 Whats new in 0.9
  CHANGELOG.rst
  RELEASE.rst
  docs/whatsnew/0.9.rst
  docs/whatsnew/index.rst
Labels: Documentation, Priority High
