Repository sunpy/sunpy, pull requests merged in 2018-09, with the labels that each got.

#2742 Fix CI by removing nomlk
  .travis.yml
  appveyor.yml
Labels: No Changelog Entry Needed

#2743 force figure tests mpl backend to Agg
  .circleci/config.yml
Labels: Merge When CI Passes, No Changelog Entry Needed, [BugFix]

#2735 Revert disallowing a no-op HPC<>HPC transformation without obstime
  sunpy/coordinates/tests/test_transformations.py
  sunpy/coordinates/transformations.py
Labels: Affects Dev, No Changelog Entry Needed, [BugFix]

#2736 Add in missing space!
  sunpy/net/jsoc/jsoc.py
Labels: Merge When CI Passes, No Changelog Entry Needed, [DocFix]

#2737 Add VSO and JSOC links to FIDO docs
  docs/guide/acquiring_data/fido.rst
Labels: Merge When CI Passes, No Changelog Entry Needed, [DocFix]

#2739 Remove py2 check for pathlib
  sunpy/net/dataretriever/client.py
Labels: Merge When CI Passes, No Changelog Entry Needed, [BugFix]

#2749 Aiaprep fix
  changelog/2749.bugfix.rst
  sunpy/instr/aia.py
  sunpy/instr/tests/test_aia.py
Labels: [BugFix], map

#2682 Contribution guidelines for the SunPy Example Gallery
  changelog/2682.doc.rst
  docs/dev_guide/example_gallery.rst
  docs/dev_guide/index.rst
Labels: Examples, Merge When CI Passes, [DocFix]

#2731 Changes to LASCO color tables
  changelog/2731.breaking.rst
  changelog/2731.bugfix.rst
  sunpy/cm/cm.py
  sunpy/cm/color_tables.py
Labels: Merge When CI Passes, map

#2751 [0.9] v0.9.3 backports
  .circleci/config.yml
  .circleci/early_exit.sh
  .travis.yml
  CHANGELOG.rst
  appveyor.yml
  changelog/2702.bugfix.rst
  docs/dev_guide/example_gallery.rst
  docs/dev_guide/index.rst
  docs/guide/acquiring_data/fido.rst
  setup.py
  sunpy/coordinates/tests/test_transformations.py
  sunpy/coordinates/tests/test_transformations_comparision.py
  sunpy/coordinates/transformations.py
  sunpy/instr/aia.py
  sunpy/instr/tests/test_aia.py
  sunpy/io/fits.py
  sunpy/io/tests/test_fits.py
  sunpy/net/jsoc/jsoc.py
  sunpy/physics/differential_rotation.py
Labels: 0.9.x, No Changelog Entry Needed

#2754 Functionality to convert hpc to hcc with different observer and vice versa issue: #2712
  changelog/2754.bugfix.rst
  sunpy/coordinates/tests/test_transformations.py
  sunpy/coordinates/transformations.py
Labels: coordinates

#2766 Make sure package does not import itself during setup
  sunpy/__init__.py
Labels: No Changelog Entry Needed, [BugFix]
