Repository sunpy/sunpy, pull requests merged in 2018-10, with the labels that each got.

#2767 Fix deprecation warning for SafeConfigParser
  sunpy/util/config.py
Labels: No Changelog Entry Needed, [BugFix]

#2651 [0.9] Fix bug in calculating LYRA measurement times.
  changelog/2651.bugfix.rst
  sunpy/lightcurve/sources/lyra.py
  sunpy/timeseries/sources/lyra.py
Labels: 0.9.x, [BugFix], timeseries

#2778 Make get_cmap deprecation warning clearer
  sunpy/cm/cm.py
Labels: No Changelog Entry Needed

#2779 Nicer warnings for non-present packages during doc build
  docs/conf.py
Labels: No Changelog Entry Needed, [CodeFix]

#2770 Fix/copyedit outdated documentation
  changelog/2770.doc.rst
  examples/plotting/solar_cycle_example.py
Labels: [DocFix]

#2780 cube > sequence in example
  examples/maps/base_and_running_difference_mapcubes.py
Labels: No Changelog Entry Needed, [CodeFix]

#2718 Remove future imports from examples
  examples/acquiring_data/2011_06_07_sampledata_overview.py
  examples/acquiring_data/skip_searching_vso.py
  examples/computer_vision_techniques/finding_masking_bright_pixels.py
  examples/computer_vision_techniques/loop_edge_enhance.py
  examples/computer_vision_techniques/mask_disk.py
  examples/computer_vision_techniques/off_limb_enhance.py
  examples/maps/brightness_pixel_location.py
  examples/maps/image_bright_regions_gallery_example.py
  examples/maps/map_data_histogram.py
  examples/maps/map_from_numpy_array.py
  examples/maps/map_resampling_and_superpixels.py
  examples/maps/map_rotation.py
  examples/maps/maps_example.py
  examples/maps/submaps_and_cropping.py
  examples/plotting/aia_example.py
  examples/plotting/great_arc_example.py
  examples/plotting/lat_lon_lines.py
  examples/plotting/map_editcolormap.py
  examples/plotting/overplot_hek_polygon.py
  examples/plotting/simple_differential_rotation.py
  examples/plotting/skip_magnetogram_active_regions.py
  examples/plotting/solar_cycle_example.py
  examples/time_series/goes_hek_m25.py
  examples/time_series/skip_timeseries_example.py
  examples/time_series/skip_timeseriesmetadata_example.py
  examples/units_and_coordinates/AIA_limb_STEREO.py
  examples/units_and_coordinates/SDO_to_STEREO_Coordinate_Conversion.py
Labels: No Changelog Entry Needed, [DocFix]

#2665 GitHub Issue and PR Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/standard_pull_request.md
Labels: No Changelog Entry Needed

#2783 rename PR template so it should work
  .github/pull_request_template.md
Labels: No Changelog Entry Needed, [CodeFix]

#2775 Fix LASCOMap
  changelog/2775.bugfix.rst
  sunpy/map/sources/soho.py
Labels: Merge When CI Passes, [BugFix], map

#2786 should fix up the cron figure test
  .travis.yml
Labels: No Changelog Entry Needed

#2792 GitHub Template Update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  changelog/2771.bugfix.rst
  sunpy/net/helioviewer.py
  sunpy/util/net.py
Labels: No Changelog Entry Needed

#2701 Replace all instances of quantity_allclose with u.allclose
  changelog/2701.bugfix.rst
  setup.py
  sunpy/coordinates/frames.py
  sunpy/coordinates/transformations.py
  sunpy/tests/figure_hashes_py36.json
  sunpy/tests/figure_tests_env_py36.yml
Labels: [BugFix]

#2798 Make pep8speaks be a little less verbose
  .pep8speaks.yml
Labels: No Changelog Entry Needed

#2765 Small documentation update
  changelog/2765.doc.rst
  docs/dev_guide/newcomers.rst
  docs/guide/index.rst
Labels: [DocFix]

#2805 pin numpy for doc build
  .circleci/config.yml
Labels: Merge When CI Passes, No Changelog Entry Needed

#2793 Instantiate map with array and WCS object
  changelog/2793.feature.rst
  sunpy/map/map_factory.py
  sunpy/map/tests/test_map_factory.py
  sunpy/util/tests/test_util.py
Labels: map

#2699 Update our packaging stuff from the template
  .circleci/config.yml
  setup.cfg
  setup.py
  sunpy/__init__.py
  sunpy/tests/figure_tests_env_py36.yml
Labels: Merge When CI Passes, No Changelog Entry Needed, [Review]

#2811 Fix setup.py to be Python 2 / <3.6 compatible for error printing reasons
  setup.py
Labels: No Changelog Entry Needed

#2815 Changelog build in docs and numpy version for rtd
  docs/conf.py
  requirements/base.txt
Labels: Merge When CI Passes, No Changelog Entry Needed

#2816 forgot to add it as dep to rtd
  docs/conf.py
  requirements/docs.txt
Labels: No Changelog Entry Needed

#2817 Improve the way we deal with towncrier in the docs
  .gitignore
  README.rst
  changelog/2717.breaking.rst
  docs/conf.py
  docs/whatsnew/changelog.rst
  licenses/TOWNCRIER.rst
  sunpy/util/towncrier.py
Labels: No Changelog Entry Needed

#2813 DOC: Add missing plot to end of units and coordinates guide
  changelog/2813.doc.rst
  docs/guide/units-coordinates.rst
Labels: [DocFix]

#2820 fix doctests
  .travis.yml
  appveyor.yml
  docs/code_ref/coordinates.rst
  docs/guide/acquiring_data/database.rst
  docs/guide/data_types/maps.rst
  docs/guide/units-coordinates.rst
  requirements/docs.txt
Labels: Merge When CI Passes, No Changelog Entry Needed
