Repository sunpy/sunpy, pull requests merged in 2019-08, with the labels that each got.

#3290 Reverted the return arguments for ImageAnimatorWCS example
  examples/plotting/imageanimatorwcs.py
Labels: Merge When CI Passes, No Changelog Entry Needed, [BugFix]

#3299 Removed Travis config and fixed some minor CI issues.
  .travis.yml
  README.rst
  azure-pipelines.yml
  examples/plotting/imageanimatorwcs.py
  sunpy/coordinates/tests/test_transformations.py
  tox.ini
Labels: Infrastructure, No Changelog Entry Needed, [CodeFix]

#3304 Bye Bye Travis
  .travis.yml
Labels: Infrastructure, No Changelog Entry Needed

#3309 pin pytest version
  setup.cfg
  tox.ini
Labels: Infrastructure, No Changelog Entry Needed, Tests, [CodeFix]

#3312 dev astropyquery for dev astropy
  tox.ini
Labels: Infrastructure, No Changelog Entry Needed, [CodeFix]

#3305 Fixed bugs with our frame->WCS mapping
  changelog/3305.bugfix.1.rst
  changelog/3305.bugfix.2.rst
  sunpy/coordinates/frames.py
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/coordinates/wcs_utils.py
Labels: [BugFix], coordinates

#3280 Add disable progress bar feature, edit docstrings
  changelog/3280.feature.rst
  sunpy/net/helioviewer.py
  sunpy/net/tests/test_helioviewer.py
Labels: Feature Request, net

#3291 Fixed observer-related bugs
  changelog/3291.bugfix.1.rst
  changelog/3291.bugfix.2.rst
  changelog/3291.bugfix.3.rst
  sunpy/coordinates/frames.py
  sunpy/coordinates/tests/test_frames.py
  sunpy/coordinates/tests/test_transformations.py
  sunpy/coordinates/transformations.py
  sunpy/coordinates/utils.py
Labels: [BugFix], coordinates

#3315 circleci update
  .circleci/config.yml
Labels: Infrastructure, No Changelog Entry Needed

#3320 update docs and fix init format
  docs/conf.py
  examples/units_and_coordinates/skip_AIA_limb_STEREO.py
  examples/units_and_coordinates/skip_SDO_to_STEREO_Coordinate_Conversion.py
  setup.cfg
  sunpy/__init__.py
Labels: Infrastructure, No Changelog Entry Needed, [CodeFix]

#3298 Use `parfive.Results`, not `downloader.download()`
  changelog/3298.bugfix.rst
  sunpy/net/tests/test_vso.py
  sunpy/net/vso/vso.py
Labels: [BugFix], net

#3317 Overhaul of coordinate-frame docstrings
  sunpy/coordinates/frames.py
Labels: No Changelog Entry Needed, [DocFix], coordinates

#3212 New coordinate frames! (HEE, GSE, HCI, and GEI)
  changelog/3212.feature.rst
  sunpy/coordinates/frames.py
  sunpy/coordinates/tests/test_transformations.py
  sunpy/coordinates/transformations.py
Labels: [Review], coordinates
