Repository sunpy/sunpy, pull requests merged in 2019-03, with the labels that each got.

#2953 Modify isort config to only sort stdlib by line length
  setup.cfg
Labels: No Changelog Entry Needed

#2950 Fix most warnings in sunpy.image tests
  sunpy/image/tests/test_transform.py
Labels: Merge When CI Passes, No Changelog Entry Needed, Tests, [CodeFix]

#2936 Changed Pandas DataFrames in sunpy/sun/models.py to Astropy Tables.
  changelog/2936.breaking.rst
  sunpy/sun/models.py
Labels: Refactoring, [Review], sun

#2955 Add test and coverage reporting to Azure
  azure-templates.yml
Labels: No Changelog Entry Needed, [CodeFix]

#2957 Fixed Most Warnings in sunpy.io
  sunpy/instr/tests/test_aia.py
  sunpy/io/tests/test_filetools.py
  sunpy/map/tests/test_map_factory.py
Labels: No Changelog Entry Needed, [CodeFix]

#2954 move to setuptools_scm
  .gitignore
  MANIFEST.in
  azure-pipelines.yml
  changelog/2954.breaking.rst
  docs/conf.py
  pyproject.toml
  setup.cfg
  setup.py
  sunpy/__init__.py
  sunpy/data/setup_package.py
  sunpy/database/setup_package.py
  sunpy/extern/setup_package.py
  sunpy/io/special/asdf/setup_package.py
  sunpy/tests/coveragerc
  sunpy/tests/setup_package.py
  sunpy/version.py
  tox.ini
Labels: Merge When CI Passes, [CodeFix]

#2960 version fix for doc builds and tox test changes
  .circleci/config.yml
  .gitignore
  MANIFEST.in
  azure-pipelines.yml
  conftest.py
  docs/conf.py
  setup.cfg
  sunpy/conftest.py
  sunpy/data/test/__init__.py
  sunpy/instr/fermi.py
  sunpy/instr/goes.py
  sunpy/net/dataretriever/tests/test_noaa.py
  sunpy/net/tests/test_fido.py
  tox.ini
Labels: Merge When CI Passes, No Changelog Entry Needed

#2956 Subclassed DeprecationWarning in exceptions.py
  sunpy/util/exceptions.py
Labels: No Changelog Entry Needed, [CodeFix]

#2965 added init files to dirs missing them
  sunpy/cm/tests/__init__.py
  sunpy/map/sources/tests/__init__.py
  sunpy/physics/tests/__init__.py
  sunpy/roi/tests/__init__.py
  sunpy/util/exceptions.py
Labels: No Changelog Entry Needed, [CodeFix]

#2973 Remove test warnings in sunpy.roi
  sunpy/roi/tests/test_chaincode.py
Labels: No Changelog Entry Needed, Refactoring, [CodeFix]

#2969 Made HEC treat start_time and end_time as astropy.time.Time objects
  changelog/2969.bugfix.rst
  sunpy/net/helio/hec.py
  sunpy/net/tests/test_helio.py
Labels: [BugFix], net

#2922 moved to using appdirs for sunpyrc config
  changelog/2922.trivial.rst
  sunpy/data/sunpyrc
  sunpy/extern/README.rst
  sunpy/extern/appdirs.py
  sunpy/extern/appdirs_license.txt
  sunpy/util/config.py
  sunpy/util/tests/test_config.py
  tox.ini
Labels: Merge When CI Passes, Refactoring, [Review], util

#2976 Fixed docstring and improved readability of hec.py
  sunpy/net/helio/hec.py
Labels: Refactoring, [CodeFix], net

#2978 Updating UnsupportedPythonError(f"sunpy does not support Python < {__…
  sunpy/__init__.py
Labels: [CodeFix]

#2968 Unskipped all gallery examples
  .circleci/config.yml
  azure-templates.yml
  docs/Makefile
  docs/make.bat
  examples/acquiring_data/searching_vso.py
  examples/plotting/magnetogram_active_regions.py
  examples/time_series/timeseries_example.py
  examples/time_series/timeseriesmetadata_example.py
  setup.cfg
  sunpy/instr/tests/test_fermi.py
  sunpy/net/dataretriever/sources/noaa.py
  sunpy/net/tests/test_helio.py
  tox.ini
Labels: Merge When CI Passes, No Changelog Entry Needed, [DocFix]

#2946 Mapbase converts crln_obs to hgln_obs if it is found in the header
  changelog/2946.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: [BugFix], map

#2867 ImageAnimator axis_ranges refactor 2
  changelog/2867.breaking.rst
  examples/plotting/LineAnimator_examples.py
  sunpy/visualization/animator/base.py
  sunpy/visualization/animator/image.py
  sunpy/visualization/animator/line.py
  sunpy/visualization/animator/tests/test_basefuncanimator.py
Labels: Refactoring, [Review], visualization

#2987 Changed test_online_fido to be much faster
  sunpy/net/dataretriever/sources/rhessi.py
  sunpy/net/tests/strategies.py
  sunpy/net/tests/test_fido.py
  tox.ini
Labels: No Changelog Entry Needed, Refactoring, [CodeFix]

#2988 Dcoument default kwarg values for MapFactory
  sunpy/map/map_factory.py
Labels: No Changelog Entry Needed, [DocFix], map

#2797 Replace SunPy's Downloader with an asyncio version
  .circleci/config.yml
  changelog/2797.breaking.rst
  changelog/2797.feature.rst
  docs/code_ref/util.rst
  docs/conf.py
  docs/guide/acquiring_data/fido.rst
  setup.cfg
  sunpy/database/database.py
  sunpy/net/base_client.py
  sunpy/net/dataretriever/client.py
  sunpy/net/dataretriever/sources/noaa.py
  sunpy/net/dataretriever/tests/test_eve.py
  sunpy/net/dataretriever/tests/test_goes_ud.py
  sunpy/net/dataretriever/tests/test_lyra_ud.py
  sunpy/net/dataretriever/tests/test_noaa.py
  sunpy/net/dataretriever/tests/test_norh.py
  sunpy/net/download.py
  sunpy/net/fido_factory.py
  sunpy/net/hek2vso/hek2vso.py
  sunpy/net/helioviewer.py
  sunpy/net/jsoc/jsoc.py
  sunpy/net/jsoc/tests/test_jsoc.py
  sunpy/net/proxyfix.py
  sunpy/net/tests/strategies.py
  sunpy/net/tests/test_download.py
  sunpy/net/tests/test_fido.py
  sunpy/net/tests/test_helioviewer.py
  sunpy/net/tests/test_vso.py
  sunpy/net/vso/vso.py
  sunpy/util/net.py
  sunpy/util/progressbar.py
  sunpy/util/util.py
  tox.ini
Labels: [Review], net

#2926 Simplified user access to the sourceID variable in the HelioviewerClient.
  changelog/2926.trivial.rst
  sunpy/net/helioviewer.py
  sunpy/util/tests/test_util.py
  sunpy/util/util.py
Labels: Refactoring, [Review], net

#2847 Don't assume arcseconds when CUNIT metadata isn't present
  changelog/2847.breaking.rst
  docs/code_ref/map.rst
  docs/guide/data_types/maps.rst
  examples/map/map_from_numpy_array.py
  examples/map/maps_example.py
  sunpy/map/map_factory.py
  sunpy/map/mapbase.py
  sunpy/map/sources/iris.py
  sunpy/map/sources/rhessi.py
  sunpy/map/sources/sdo.py
  sunpy/map/sources/soho.py
  sunpy/map/sources/tests/test_iris_source.py
  sunpy/map/sources/tests/test_mdi_source.py
  sunpy/map/sources/tests/test_trace_source.py
  sunpy/map/sources/trace.py
  sunpy/map/tests/test_map_factory.py
  sunpy/map/tests/test_mapbase.py
Labels: Merge When CI Passes, Refactoring, [Review], map

#2995 Docs clean up
  sunpy/net/helioviewer.py
Labels: No Changelog Entry Needed, [DocFix], net

#2994 Some more Python 2 cleanup
  changelog/2994.removal.rst
  docs/guide/data_types/maps.rst
  sunpy/database/database.py
  sunpy/io/src/ana/_pyana.c
  sunpy/map/map_factory.py
  sunpy/map/mapsequence.py
  sunpy/physics/transforms/__init__.py
  sunpy/physics/transforms/differential_rotation.py
  sunpy/physics/transforms/solar_rotation.py
Labels: Refactoring, [CodeFix]

#2982 Fixes issue-2981 by raising a ConnectionError
  changelog/2981.trivial.rst
  docs/guide/acquiring_data/database.rst
  sunpy/net/tests/test_vso.py
  sunpy/net/vso/vso.py
Labels: [BugFix], net

#3005 made tests use default config
  sunpy/conftest.py
  sunpy/util/config.py
  sunpy/util/tests/test_config.py
Labels: No Changelog Entry Needed, [BugFix]

#2980 Adding Logger to SunPy
  changelog/2980.feature.1.rst
  changelog/2980.feature.rst
  docs/dev_guide/index.rst
  docs/dev_guide/logger.rst
  docs/guide/index.rst
  docs/guide/logger.rst
  sunpy/__init__.py
  sunpy/data/_sample.py
  sunpy/data/sunpyrc
  sunpy/image/coalignment.py
  sunpy/image/tests/test_coalignment.py
  sunpy/image/tests/test_transform.py
  sunpy/image/transform.py
  sunpy/io/fits.py
  sunpy/map/mapbase.py
  sunpy/net/jsoc/jsoc.py
  sunpy/net/vso/vso.py
  sunpy/roi/chaincode.py
  sunpy/timeseries/metadata.py
  sunpy/timeseries/sources/eve.py
  sunpy/timeseries/timeseriesbase.py
  sunpy/util/config.py
  sunpy/util/decorators.py
  sunpy/util/exceptions.py
  sunpy/util/logger.py
  sunpy/util/multimethod.py
  sunpy/util/tests/test_logger.py
Labels: Merge When CI Passes, Refactoring, [Review]

#3008 Add alphabetical sorting to release script
  .gitignore
  tools/generate_releaserst.xsh
Labels: No Changelog Entry Needed, [CodeFix]

#2951 Updated developer documenation
  CITATION.rst
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.rst
  MANIFEST.in
  README.rst
  RELEASE.rst
  changelog/2951.doc.rst
  changelog/README.rst
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/_templates/layout.html
  docs/about.rst
  docs/code_of_conduct.rst
  docs/conf.py
  docs/dev_guide/code_standards.rst
  docs/dev_guide/config.rst
  docs/dev_guide/documentation.rst
  docs/dev_guide/example_gallery.rst
  docs/dev_guide/funding.rst
  docs/dev_guide/index.rst
  docs/dev_guide/maintainer_workflow.rst
  docs/dev_guide/new_objects.rst
  docs/dev_guide/newcomers.rst
  docs/dev_guide/pr_review_procedure.rst
  docs/dev_guide/tests.rst
  docs/dev_guide/units_quantities.rst
  docs/dev_guide/version_control.rst
  docs/index.rst
  docs/whatsnew/0.8.rst
  docs/whatsnew/0.9.rst
  docs/whatsnew/1.0.rst
  docs/whatsnew/index.rst
  examples/README.txt
  examples/acquiring_data/README.txt
  examples/computer_vision_techniques/README.txt
  examples/example_template/example_template.py
  examples/map/README.txt
  examples/map/composite_map_AIA_HMI.py
  examples/plotting/README.txt
  examples/plotting/solar_cycle_example.py
  examples/saving_and_loading_data/README.txt
  examples/time_series/README.txt
  examples/units_and_coordinates/README.txt
  licenses/README.rst
  licenses/SIX.rst
Labels: Documentation, [Review]

#2996 sunpy.visialization python files clean up
  sunpy/visualization/__init__.py
  sunpy/visualization/animator/__init__.py
  sunpy/visualization/animator/base.py
  sunpy/visualization/animator/image.py
  sunpy/visualization/animator/line.py
  sunpy/visualization/animator/mapsequenceanimator.py
  sunpy/visualization/animator/tests/test_basefuncanimator.py
  sunpy/visualization/visualization.py
  sunpy/visualization/wcsaxes_compat.py
Labels: Documentation, No Changelog Entry Needed, [Review], visualization

#3010 Fixed missing positional argument while calling function
  sunpy/visualization/animator/base.py
Labels: No Changelog Entry Needed, [BugFix], visualization

#2979 Added tests for sunpy/net/hek/hek.py
  sunpy/net/tests/test_hek.py
Labels: No Changelog Entry Needed, Tests, net

#2983 Fermi client fix
  changelog/2983.bugfix.rst
  sunpy/net/attrs.py
  sunpy/net/dataretriever/__init__.py
  sunpy/net/dataretriever/sources/fermi_gbm.py
  sunpy/net/dataretriever/tests/test_fermi_gbm.py
Labels: Merge When CI Passes, [Review], net

#2974 Added unit tests for Helio submodule
  sunpy/net/tests/test_helio.py
Labels: No Changelog Entry Needed, Tests, net

#3011 Fix for example hmi.py
  examples/acquiring_data/hmi.py
  sunpy/database/tests/test_tables.py
Labels: No Changelog Entry Needed, [DocFix]

#2986 Improve scaling of animator and adding aspect keyword to lineanimator
  sunpy/visualization/animator/base.py
  sunpy/visualization/animator/line.py
Labels: No Changelog Entry Needed, [BugFix], visualization

#3013 Modify `edges_to_centers_nd` calls in `base.py`
  sunpy/visualization/animator/base.py
Labels: No Changelog Entry Needed, [BugFix]

#3014 doc version the wrong way
  docs/conf.py
Labels: No Changelog Entry Needed, [DocFix]

#3017 Update the mailmap
  .mailmap
  tools/generate_releaserst.xsh
Labels: No Changelog Entry Needed, [CodeFix]

#3019 Document that Helioprojective observer can be a string
  sunpy/coordinates/frames.py
Labels: No Changelog Entry Needed, [DocFix]

#3022 Trick GitHub into seeing we have a code of conduct for the repo
  .github/CODE_OF_CONDUCT.md
  .mailmap
Labels: No Changelog Entry Needed

#3024 ci and doc string fix
  .travis.yml
  sunpy/coordinates/frames.py
  tox.ini
Labels: No Changelog Entry Needed, [CodeFix]

#3001 sunpy.sun python file review
  .circleci/config.yml
  changelog/3001.breaking.rst
  docs/code_ref/coordinates.rst
  docs/dev_guide/tests.rst
  docs/guide/tour.rst
  docs/guide/units-coordinates.rst
  sunpy/coordinates/frames.py
  sunpy/coordinates/tests/test_frameattributes.py
  sunpy/io/special/asdf/schemas/sunpy.org/sunpy/coordinates/frames/helioprojective-1.0.0.yaml
  sunpy/physics/differential_rotation.py
  sunpy/physics/tests/test_differential_rotation.py
  sunpy/physics/tests/test_solar_rotation.py
  sunpy/sun/__init__.py
  sunpy/sun/_constants.py
  sunpy/sun/constants.py
  sunpy/sun/models.py
  sunpy/sun/sun.py
  sunpy/sun/tests/test_constants.py
  sunpy/sun/tests/test_sun.py
  sunpy/tests/figure_hashes_py36.json
Labels: Documentation, Merge When CI Passes, [Review], sun

#3025 Catch some more warnings
  sunpy/coordinates/frames.py
  sunpy/database/tests/test_tables.py
  sunpy/instr/aia.py
  sunpy/instr/goes.py
  sunpy/io/tests/test_fits.py
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
  sunpy/physics/differential_rotation.py
Labels: Merge When CI Passes, No Changelog Entry Needed, [CodeFix]

#3016 Remove some warnings from timeseries tests
  sunpy/timeseries/tests/test_timeseriesbase.py
  sunpy/timeseries/timeseriesbase.py
Labels: No Changelog Entry Needed, Refactoring, Tests, [CodeFix]
