Repository sunpy/sunpy, pull requests merged in 2020-06, with the labels that each got.

#4226 Reduced the tolerance of affine-transform tests to avoid numerical-precision issues
  sunpy/image/tests/test_transform.py
Labels: Merge When CI Passes, No Changelog Entry Needed, Tests, [CodeFix], backport 2.0

#4223 fixed the last two attrs issue with overkill
  docs/dev_guide/code_standards.rst
  docs/guide/acquiring_data/fido.rst
  docs/guide/acquiring_data/jsoc.rst
  sunpy/extern/inflect.py
  sunpy/extern/inflect_license.txt
  sunpy/net/_attrs.py
  sunpy/net/attr.py
  sunpy/net/tests/test_attr.py
Labels: No Changelog Entry Needed, backport 2.0

#4107 Adds the possibility to input a regular expression to the scrapper call
  changelog/4107.feature.rst
  sunpy/util/scraper.py
  sunpy/util/tests/test_scraper.py
Labels: backport 2.0, util

#4196 Edit the manifest file
  .gitmodules
  MANIFEST.in
  joss_paper/author_processing.py
  joss_paper/joss_paper_plot.pdf
  joss_paper/joss_paper_plot.py
  joss_paper/matplotlibrc
  joss_paper/metadata.yml
  joss_paper/paper.bib
  joss_paper/paper.md
  setup.cfg
  tox.ini
Labels: Infrastructure, Merge When CI Passes, No Changelog Entry Needed, [CodeFix], backport 2.0

#4179 Check for unintended behavior on pixels instead of coords
  sunpy/coordinates/utils.py
  sunpy/map/mapbase.py
Labels: No Changelog Entry Needed, backport 2.0

#4239 Fixed very small inaccuracy with sun.angular_radius()
  changelog/4239.bugfix.rst
  sunpy/coordinates/sun.py
  sunpy/coordinates/tests/test_sun.py
Labels: backport 2.0, coordinates

#4235 Various fixes to affine-transform unit tests
  sunpy/image/tests/test_transform.py
Labels: No Changelog Entry Needed, Tests, backport 2.0

#4197 Improve submap argument parsing
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: No Changelog Entry Needed, backport 2.0

#4214 Update zenodo.json for 2.0
  .mailmap
  .zenodo.json
  tools/update_zenodo.py
Labels: No Changelog Entry Needed, [CodeFix], backport 2.0

#4169 Remove NOAA solar cycle sample data
  changelog/4169.docfix.rst
  changelog/4169.removal.rst
  examples/plotting/solar_cycle_example.py
  examples/time_series/skip_timeseries_example.py
  examples/time_series/timeseries_convolution_filter.py
  examples/time_series/timeseries_peak_finding.py
  sunpy/data/_sample.py
  sunpy/timeseries/sources/noaa.py
Labels: Examples, backport 2.0

#4251 astropy units import missed in exmaple
  sunpy/net/dataretriever/sources/norh.py
Labels: Documentation, No Changelog Entry Needed, backport 2.0

#4240 🔧 Changed HELIO online tests to iterate over available servers
  sunpy/net/helio/hec.py
  sunpy/net/helio/parser.py
  sunpy/net/helio/tests/test_helio.py
Labels: Merge When CI Passes, No Changelog Entry Needed, backport 2.0

#4256 Ensure that SunpyDeprecationWarnings are raised as errors in the test suite
  examples/computer_vision_techniques/loop_edge_enhance.py
  examples/map/composite_map_AIA_HMI.py
  examples/map/submaps_and_cropping.py
  examples/plotting/finegrained_plot.py
  examples/plotting/wcsaxes_map_example.py
  examples/units_and_coordinates/SDO_to_STEREO_Coordinate_Conversion.py
  examples/units_and_coordinates/venus_transit.py
  setup.cfg
  sunpy/conftest.py
  sunpy/image/tests/test_coalignment.py
  sunpy/instr/tests/test_aia.py
  sunpy/map/tests/test_maputils.py
  sunpy/net/vso/tests/test_vso.py
  sunpy/physics/differential_rotation.py
  sunpy/physics/tests/test_differential_rotation.py
Labels: Infrastructure, No Changelog Entry Needed, [BugFix], backport 2.0

#4260 Fix y-pixel ordering in submap
  sunpy/map/mapbase.py
Labels: No Changelog Entry Needed, [BugFix], [CodeFix], backport 2.0

#4275 Fix some time comparisions in tests
  sunpy/instr/goes.py
  sunpy/instr/tests/test_lyra.py
Labels: No Changelog Entry Needed, Tests, [CodeFix], backport 2.0

#4231 Add rotated map plotting test
  sunpy/map/tests/test_plotting.py
  sunpy/tests/figure_hashes_py36.json
  sunpy/tests/figure_hashes_py37.json
Labels: No Changelog Entry Needed, Tests, backport 2.0, map

#4165 What's New in 2.0
  docs/guide/acquiring_data/fido.rst
  docs/whatsnew/2.0.rst
  docs/whatsnew/index.rst
Labels: Documentation, No Changelog Entry Needed, backport 2.0

#4267 Fixed missing transformation errors when `obstime` is `None`
  changelog/4267.bugfix.rst
  docs/whatsnew/2.0.rst
  sunpy/coordinates/tests/test_transformations.py
  sunpy/coordinates/transformations.py
Labels: Merge When CI Passes, [BugFix], backport 2.0, coordinates

#4271 Move the figure test builds away from tox-conda
  .circleci/config.yml
  pyproject.toml
  setup.cfg
  sunpy/tests/figure_hashes_mpl_321_ft_261_astropy_401post1.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
  sunpy/tests/hash.py
  tox.ini
Labels: Infrastructure, Merge When CI Passes, No Changelog Entry Needed

#4289 Don't default to py_36 for toxenv in figure comparisons
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
  sunpy/tests/helpers.py
Labels: No Changelog Entry Needed, [CodeFix]

#4288 Fixed wrong satno. in XRS overlap URLs
  changelog/4288.bugfix.rst
  sunpy/net/dataretriever/sources/goes.py
  sunpy/net/dataretriever/sources/tests/test_goes_ud.py
Labels: [BugFix], backport 2.0

#4295 Do not install any dependencies via pip under tox conda
  tox.ini
Labels: Infrastructure, No Changelog Entry Needed, [CodeFix], backport 2.0

#4284 Drop support for Python 3.6
  azure-pipelines.yml
  changelog/4284.breaking.rst
  docs/dev_guide/code_standards.rst
  docs/dev_guide/example_gallery.rst
  docs/dev_guide/tests.rst
  docs/guide/installation/advanced.rst
  docs/guide/installation/index.rst
  setup.cfg
  sunpy/__init__.py
  tox.ini
Labels: Infrastructure, [CodeFix]

#4297 Force software version when saving pngs in testing
  sunpy/tests/figure_hashes_mpl_321_ft_261_astropy_401post1.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
  sunpy/tests/helpers.py
Labels: Infrastructure, No Changelog Entry Needed, [CodeFix], backport 2.0

#4299 Switch to using conda-forge for tox conda build
  tox.ini
Labels: Infrastructure, No Changelog Entry Needed, [CodeFix], backport 2.0

#4303 Improve some error messages in sunpy.data.manager
  sunpy/data/data_manager/manager.py
Labels: No Changelog Entry Needed, backport 2.0

#4306 Fix MapSequence doc
  sunpy/map/mapsequence.py
Labels: Documentation, No Changelog Entry Needed, [DocFix], backport 2.0, map

#4310 Transition doc build to RTD
  .circleci/config.yml
  readthedocs.yml
Labels: Infrastructure, No Changelog Entry Needed

#4305 Move data manger example to a gallery folder
  docs/conf.py
  examples/developer_tools/README.txt
  examples/developer_tools/remote_data_manager.py
Labels: Examples, No Changelog Entry Needed, [DocFix], backport 2.0

#4308 Improve missing observer transformation errors
  sunpy/coordinates/transformations.py
Labels: No Changelog Entry Needed, backport 2.0, coordinates

#4315 add importlib_metadata as python<3.8 core dep
  .circleci/config.yml
  setup.cfg
Labels: No Changelog Entry Needed, [CodeFix], backport 2.0

#4316 RTD broken due to plotting
  readthedocs.yml
  rtd-environment.yml
  sunpy/data/_sample.py
  sunpy/timeseries/sources/eve.py
Labels: No Changelog Entry Needed, [DocFix], backport 2.0

#4274 Add base coordinate frames to docs
  changelog/4274.docfix.rst
  sunpy/coordinates/frames.py
  sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py
Labels: backport 2.0, coordinates

#4309 Added a show method for base_Client
  changelog/4309.feature.rst
  sunpy/net/base_client.py
  sunpy/net/dataretriever/sources/tests/test_eve.py
  sunpy/net/dataretriever/sources/tests/test_fermi_gbm.py
  sunpy/net/dataretriever/sources/tests/test_goes_suvi.py
  sunpy/net/dataretriever/sources/tests/test_goes_ud.py
  sunpy/net/dataretriever/sources/tests/test_lyra_ud.py
  sunpy/net/dataretriever/sources/tests/test_noaa.py
  sunpy/net/dataretriever/sources/tests/test_norh.py
  sunpy/net/dataretriever/sources/tests/test_rhessi.py
  sunpy/net/jsoc/tests/test_jsoc.py
  sunpy/net/vso/tests/test_vso.py
Labels: net

#4313 Added method to extract metadata from url using parse
  changelog/4313.feature.rst
  setup.cfg
  sunpy/extern/parse.py
  sunpy/extern/parse_license.txt
  sunpy/util/scraper.py
  sunpy/util/tests/test_scraper.py
Labels: net, util

#4325 Update dev image hashes
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
Labels: No Changelog Entry Needed

#4264 Remove warnings from test_mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: No Changelog Entry Needed, Tests

#4326 Use default mpl colour cycle for RHESSI peek
  changelog/4326.feature.rst
  sunpy/tests/figure_hashes_mpl_321_ft_261_astropy_401post1.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
  sunpy/timeseries/sources/rhessi.py
Labels: timeseries
