Repository sunpy/sunpy, pull requests merged in 2021-11, with the labels that each got.

#5663 Remove old workaround in QueryResponseTable
  setup.cfg
  sunpy/net/base_client.py
  sunpy/tests/figure_hashes_mpl_332_ft_261_astropy_421_animators_100.json
  tox.ini
Labels: No Changelog Entry Needed, No Backport

#5669 Move automodapi files into generated
  .gitignore
  docs/conf.py
Labels: Documentation, No Changelog Entry Needed, No Backport

#5672 Pin glymur to fix windows tests
  setup.cfg
Labels: No Changelog Entry Needed, Merge When CI Passes, Infrastructure, backport 3.0, backport 3.1

#5671 Reduce number of examples on horizons hypotheis test
  sunpy/coordinates/tests/test_ephemeris.py
Labels: No Changelog Entry Needed, backport 3.0, backport 3.1

#5677 " as far as the eye can see
  CHANGELOG.rst
  docs/guide/installation.rst
  sunpy/tests/self_test.py
Labels: [DocFix], No Changelog Entry Needed, backport 3.0, backport 3.1

#5623 Landing page improvements
  changelog/5623.doc.rst
  docs/code_ref/coordinates/index.rst
  docs/code_ref/data.rst
  docs/code_ref/database.rst
  docs/code_ref/image.rst
  docs/code_ref/index.rst
  docs/code_ref/io.rst
  docs/code_ref/map.rst
  docs/code_ref/net.rst
  docs/code_ref/physics.rst
  docs/code_ref/sun.rst
  docs/code_ref/time.rst
  docs/code_ref/timeseries.rst
  docs/code_ref/util.rst
  docs/code_ref/visualization.rst
  docs/conf.py
  docs/guide/index.rst
  docs/guide/installation.rst
  docs/index.rst
  setup.cfg
Labels: [Review], [DocFix], Merge When CI Passes, backport 3.1

#5659 Report total filesize in Fido queries
  changelog/5659.feature.rst
  docs/dev_guide/contents/extending_fido.rst
  docs/guide/acquiring_data/fido.rst
  sunpy/net/base_client.py
  sunpy/net/fido_factory.py
  sunpy/net/vso/table_response.py
Labels: [Review], Whats New?, No Backport

#5664 Skip CDF variables with zero elements
  changelog/5664.bugfix.rst
  sunpy/io/cdf.py
  sunpy/timeseries/tests/test_timeseries_factory.py
Labels: [BugFix], [Review], backport 3.1

#5682 Fix units in HMIMap.scale
  changelog/5682.bugfix.rst
  changelog/5682.trivial.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/sdo.py
  sunpy/map/sources/soho.py
Labels: [BugFix], [Review], backport 3.1

#5688 Updated comment on a test to state when a warning filter can be removed
  sunpy/map/tests/test_plotting.py
Labels: Tests, No Changelog Entry Needed

#5687 Force `_new instance` to preserve plot settings
  changelog/5687.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/tests/test_aia_source.py
  sunpy/physics/differential_rotation.py
Labels: map, [BugFix], ManualBackport, backport 3.0, backport 3.1

#5686 Don't use remote data for difference image example
  examples/map/difference_images.py
Labels: No Changelog Entry Needed, backport 3.0, backport 3.1

#5693 Backport #5687 to 3.0
  azure-pipelines.yml
  changelog/5687.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/tests/test_aia_source.py
  sunpy/physics/differential_rotation.py
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
Labels: No Changelog Entry Needed

#5694 Pyinstaller Changes
  .gitignore
  .pyinstaller/run_sunpy_tests.py
  .pyinstaller/run_tests.py
  azure-pipelines.yml
  sunpy/coordinates/tests/test_ephemeris.py
  sunpy/coordinates/tests/test_metaframes.py
  sunpy/coordinates/tests/test_offset_frame.py
  sunpy/timeseries/tests/test_timeseriesbase.py
  tox.ini
Labels: [Review], No Changelog Entry Needed, [CodeFix], Infrastructure

#5696 [3.1] Backport of #5694
  .gitignore
  .pyinstaller/run_sunpy_tests.py
  .pyinstaller/run_tests.py
  azure-pipelines.yml
  sunpy/coordinates/tests/test_ephemeris.py
  sunpy/coordinates/tests/test_metaframes.py
  sunpy/coordinates/tests/test_offset_frame.py
  sunpy/timeseries/tests/test_timeseriesbase.py
  tox.ini
Labels: No Changelog Entry Needed

#5697 [3.0] Backport of #5694
  azure-pipelines.yml
  sunpy/coordinates/tests/test_ephemeris.py
  sunpy/coordinates/tests/test_metaframes.py
  sunpy/coordinates/tests/test_offset_frame.py
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
Labels: No Changelog Entry Needed

#5698 Add a no-gallery building directive to sphinx makefile
  docs/Makefile
Labels: No Changelog Entry Needed, [CodeFix], Infrastructure

#5704 Fix database test
  sunpy/database/tests/test_tables.py
Labels: No Changelog Entry Needed, [CodeFix], backport 3.0, backport 3.1

#5655 Make `rsun` a keyword argument to get_observer_meta
  changelog/5655.feature.rst
  sunpy/map/header_helper.py
Labels: map, [Review]

#5708 Register REMOTE_DATA option
  docs/conf.py
Labels: No Changelog Entry Needed, backport 3.0, backport 3.1

#5702 Added a link to the page on calculating Carrington longitude
  sunpy/coordinates/frames.py
Labels: [DocFix], coordinates, No Changelog Entry Needed, backport 3.0, backport 3.1

#5707 Fix horizons deprecation warning
  changelog/5707.bugfix.rst
  sunpy/coordinates/ephemeris.py
Labels: [BugFix], backport 3.0, backport 3.1

#5713 Remove all usage of distutils as it is now deprecated
  changelog/5713.trivial.rst
  docs/nitpick-exceptions
  setup.cfg
  sunpy/io/setup_package.py
  sunpy/tests/helpers.py
  sunpy/timeseries/sources/goes.py
  sunpy/util/tests/test_sysinfo.py
  sunpy/version.py
Labels: Merge When CI Passes, [CodeFix], backport 3.0, backport 3.1

#5715 changelog type was wrong
  changelog/5534.doc.1.rst
  changelog/5534.doc.2.rst
Labels: [DocFix], No Changelog Entry Needed

#5700 Add support for skipping stage 2 tests
  azure-pipelines.yml
Labels: No Changelog Entry Needed, [CodeFix], Infrastructure, No Backport
