Repository sunpy/sunpy, pull requests merged in 2022-01, with the labels that each got.

#5770 Update warning ignores in setup.cfg
  docs/code_ref/coordinates/rotatedsunframe.rst
  setup.cfg
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, Merge When CI Passes, backport 3.0, backport 3.1

#5774 Backport 5770 to 3.1
  docs/code_ref/coordinates/rotatedsunframe.rst
  setup.cfg
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, Merge When CI Passes

#5773 Drop python 3.7 support
  azure-pipelines.yml
  changelog/5773.feature.rst
  docs/guide/installation.rst
  docs/whatsnew/4.0.rst
  setup.cfg
  sunpy/data/data_manager/cache.py
Labels: Whats New?, No Backport

#5767 Update .rotation_matrix doc
  sunpy/map/mapbase.py
Labels: [DocFix], No Changelog Entry Needed, backport 3.0, backport 3.1

#5763 Set a default rotation of 0deg in the header helper
  changelog/5763.bugfix.rst
  docs/guide/data_types/maps.rst
  sunpy/map/header_helper.py
  sunpy/map/tests/test_header_helper.py
Labels: map, [BugFix], backport 3.0, backport 3.1

#5769 Misc docstring fixes
  sunpy/coordinates/ephemeris.py
  sunpy/coordinates/frames.py
  sunpy/coordinates/sun.py
  sunpy/coordinates/transformations.py
  sunpy/coordinates/wcs_utils.py
  sunpy/data/_sample.py
  sunpy/data/data_manager/cache.py
  sunpy/data/data_manager/downloader.py
  sunpy/data/data_manager/manager.py
  sunpy/data/data_manager/storage.py
  sunpy/data/test/__init__.py
  sunpy/database/database.py
  sunpy/database/tables.py
  sunpy/io/fits.py
  sunpy/io/special/srs.py
  sunpy/map/compositemap.py
  sunpy/map/header_helper.py
  sunpy/map/map_factory.py
  sunpy/map/mapbase.py
  sunpy/map/mapsequence.py
  sunpy/map/maputils.py
  sunpy/net/attr.py
  sunpy/net/base_client.py
  sunpy/net/dataretriever/client.py
  sunpy/net/fido_factory.py
  sunpy/net/helio/parser.py
  sunpy/net/jsoc/jsoc.py
  sunpy/net/scraper.py
  sunpy/net/vso/legacy_response.py
  sunpy/net/vso/vso.py
  sunpy/physics/differential_rotation.py
  sunpy/physics/solar_rotation.py
  sunpy/sun/constants.py
  sunpy/time/time.py
  sunpy/time/timerange.py
  sunpy/timeseries/sources/fermi_gbm.py
  sunpy/timeseries/timeseries_factory.py
  sunpy/timeseries/timeseriesbase.py
  sunpy/util/decorators.py
  sunpy/util/net.py
  sunpy/util/tests/test_metadata.py
  sunpy/util/util.py
  sunpy/visualization/visualization.py
  sunpy/visualization/wcsaxes_compat.py
Labels: [DocFix], No Changelog Entry Needed, backport 3.0, backport 3.1

#5766 Fix CROTA > PC rotation matrix calculation
  changelog/5766.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
  sunpy/tests/figure_hashes_mpl_332_ft_261_astropy_421_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: map, [BugFix], backport 3.0, backport 3.1

#5771 Fix distutils in pyinstaller CI
  .pyinstaller/hooks/hook-sunpy.py
  .pyinstaller/run_tests.py
Labels: No Changelog Entry Needed, backport 3.1

#5782 Fix references for build_docs_ci
  docs/whatsnew/index.rst
  sunpy/map/mapsequence.py
  sunpy/sun/constants.py
Labels: [DocFix], No Changelog Entry Needed, Merge When CI Passes, backport 3.1

#5789 Update giles config for new paths
  pyproject.toml
Labels: Infrastructure

#5787 Refactor some superpixel() tests
  sunpy/map/tests/test_mapbase.py
Labels: map, No Changelog Entry Needed, [CodeFix], No Backport

#5765 Print MetaData entries on new lines
  changelog/5765.feature.rst
  docs/whatsnew/4.0.rst
  sunpy/util/metadata.py
Labels: Whats New?, No Backport

#5793 update rtd config to remove legacy or deprecated options
  .readthedocs.yaml
  readthedocs.yml
Labels: No Changelog Entry Needed, [CodeFix], Infrastructure, backport 3.0, backport 3.1

#5792 Fix SRS test
  sunpy/net/dataretriever/sources/tests/test_noaa.py
Labels: Tests, No Changelog Entry Needed, [CodeFix], backport 3.0, backport 3.1

#5791 Fix database tables test
  sunpy/database/tests/test_tables.py
Labels: Tests, No Changelog Entry Needed, [CodeFix], backport 3.0, backport 3.1

#5775 Backport #5770 to 3.0
  docs/code_ref/coordinates/rotatedsunframe.rst
  setup.cfg
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
  tox.ini
Labels: No Changelog Entry Needed, Merge When CI Passes

#5800 Backport #5763 to 3.0
  changelog/5763.bugfix.rst
  docs/guide/data_types/maps.rst
  sunpy/map/header_helper.py
  sunpy/map/tests/test_header_helper.py
Labels: No Changelog Entry Needed, Merge When CI Passes

#5802 Backport 5766 to 3.1
  changelog/5766.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
  sunpy/tests/figure_hashes_mpl_332_ft_261_astropy_42_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, Merge When CI Passes

#5801 Backport 5766 to 3.0
  changelog/5766.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
  sunpy/tests/figure_hashes_mpl_332_ft_261_astropy_42.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev.json
Labels: No Changelog Entry Needed

#5807 Return return code from self_test
  sunpy/tests/self_test.py
Labels: No Changelog Entry Needed, backport 3.0, backport 3.1

#5810 Fix for `py38-oldestdeps` Quantity equality
  sunpy/map/tests/test_mapbase.py
Labels: No Changelog Entry Needed, Merge When CI Passes, No Backport

#5814 Added citation info to readme.
  CITATION.cff
  README.rst
Labels: No Changelog Entry Needed, [CodeFix], No Backport

#5818 Fixed a warning that was always being raised as an error
  sunpy/coordinates/frames.py
Labels: [BugFix], coordinates, backport 3.0, backport 3.1

#5822 Fix pytest capture in hpc test
  sunpy/coordinates/tests/test_frames.py
Labels: CodeFix, Manual Backport, No Backport

#5829 Use TimeSeries.columns more
  sunpy/timeseries/timeseriesbase.py
Labels: No Changelog Entry Needed, CodeFix, No Backport

#5830 Fix norh plotting with pandas 1.4.0
  changelog/5830.bugfix.rst
  sunpy/timeseries/sources/norh.py
Labels: CodeFix, backport 3.0, backport 3.1

#5833 Backport #5830 to 3.0
  changelog/5830.bugfix.rst
  sunpy/timeseries/sources/norh.py
Labels: No Changelog Entry Needed

#5831 Remove references to DataFrame in timeseries plot methods
  sunpy/timeseries/sources/fermi_gbm.py
  sunpy/timeseries/sources/goes.py
  sunpy/timeseries/sources/lyra.py
  sunpy/timeseries/sources/noaa.py
  sunpy/timeseries/sources/norh.py
  sunpy/timeseries/sources/rhessi.py
Labels: DocFix, timeseries, No Changelog Entry Needed, No Backport

#5827 Prevent JSOC tests from being run in parallel
  azure-pipelines.yml
  changelog/5827.trivial.rst
  setup.cfg
  sunpy/net/jsoc/tests/test_jsoc.py
  sunpy/net/tests/test_fido.py
  tox.ini
Labels: Tests, No Backport

#5836 Stagger daily scheduled builds
  azure-pipelines.yml
Labels: No Changelog Entry Needed, backport 3.0, backport 3.1

#5838 [Backport 3.0] Stagger daily scheduled builds
  azure-pipelines.yml
Labels: No Changelog Entry Needed

#5840 Parametrize some timeseries tests
  sunpy/timeseries/tests/test_timeseriesbase.py
Labels: timeseries, No Changelog Entry Needed, CodeFix, No Backport

#5824 Improve error message when norm and v{min,max} are specified
  sunpy/map/mapbase.py
Labels: Needs review, CodeFix, backport 3.1

#5835 Raise exception if download errors during database fetch
  changelog/5835.bugfix.rst
  sunpy/database/__init__.py
  sunpy/database/database.py
  sunpy/database/tests/test_database.py
Labels: database, BugFix, Merge When CI Passes, backport 3.0, backport 3.1

#5844 Make codecov report on failing CI
  .codecov.yaml
Labels: No Changelog Entry Needed

#5816 Make horizons test more reliable
  sunpy/coordinates/tests/strategies.py
  sunpy/coordinates/tests/test_ephemeris.py
Labels: Tests, No Changelog Entry Needed, backport 3.0, backport 3.1

#5845 fixing Sun orientation in example: `Plotting a Map without any Axes`
  examples/map/plot_frameless_image.py
Labels: DocFix, Examples, No Changelog Entry Needed, backport 3.0, backport 3.1

#5854 added graphviz to rtd
  .readthedocs.yaml
Labels: No Changelog Entry Needed, CodeFix, backport 3.0, backport 3.1
