Repository sunpy/sunpy, pull requests merged in 2022-08, with the labels that each got.

#6328 Update XRTMap to handle the missing metadata for the observer
  changelog/6333.bugfix.rst
  setup.cfg
  sunpy/data/test/HinodeXRT.header
  sunpy/map/mapbase.py
  sunpy/map/sources/hinode.py
  sunpy/map/sources/tests/test_xrt_source.py
  sunpy/map/tests/test_mapbase.py
Labels: map, BugFix, backport 4.0

#6350 update metadata for pypi page
  setup.cfg
Labels: No Changelog Entry Needed, backport 4.0

#6351 Backport PR #6350 on branch 4.0 (update metadata for pypi page)
  setup.cfg
Labels: No Changelog Entry Needed, backport 4.0

#6352 Backport PR #6336 on branch 4.0 (Add bugfix release policy to docs)
  changelog/6336.doc.rst
  docs/whatsnew/index.rst
Labels: Documentation, backport 4.0

#6353 Backport PR #6329 on branch 4.0 (Update license year)
  LICENSE.rst
Labels: No Changelog Entry Needed, CodeFix, backport 4.0

#6348 [4.0] Backports #6328
  changelog/6333.bugfix.rst
  setup.cfg
  sunpy/data/test/HinodeXRT.fits
  sunpy/database/tests/test_tables.py
  sunpy/map/mapbase.py
  sunpy/map/sources/hinode.py
  sunpy/map/sources/tests/test_xrt_source.py
  sunpy/map/tests/test_mapbase.py
Labels: No Changelog Entry Needed

#6355 Add documentation on backport bot
  changelog/6355.trivial.rst
  docs/dev_guide/contents/backports.rst
  docs/dev_guide/index.rst
Labels: Documentation, DocFix, No Backport

#6357 Minor improvements to data acquisition guide
  docs/guide/acquiring_data/fido.rst
  docs/guide/acquiring_data/hek.rst
  docs/guide/acquiring_data/helioviewer.rst
  docs/guide/acquiring_data/index.rst
  docs/guide/acquiring_data/jsoc.rst
Labels: Documentation, DocFix, No Changelog Entry Needed, backport 4.0

#6365 Backport PR #6364 on branch 4.0 (Allow EVE to have two additional files in Fido search test)
  sunpy/database/tests/test_tables.py
Labels: Tests, No Changelog Entry Needed, CodeFix, backport 4.0

#6366 pin version of jsonschema
  .test_package_pins.txt
Labels: No Changelog Entry Needed, Merge When CI Passes, CodeFix, backport 4.0

#6367 Backport PR #6366 on branch 4.0 (pin version of jsonschema)
  .test_package_pins.txt
Labels: No Changelog Entry Needed, Merge When CI Passes, CodeFix, backport 4.0

#6370 Update .test_package_pins.txt
  .test_package_pins.txt
Labels: No Changelog Entry Needed, CodeFix, No Backport

#6380 Backport PR #6376 on branch 4.0 (Removes lingering use of Astropy's `matrix_product()`)
  changelog/6376.trivial.rst
  sunpy/coordinates/transformations.py
Labels: Refactoring, coordinates, CodeFix, backport 4.0

#6379 Fix Matplotlib colormap deprecation
  changelog/6379.trivial.rst
  sunpy/tests/helpers.py
  sunpy/visualization/colormaps/cm.py
Labels: visualization, CodeFix, backport 4.0

#6387 Backport PR #6379 on branch 4.0 (Fix Matplotlib colormap deprecation)
  changelog/6379.trivial.rst
  sunpy/tests/helpers.py
  sunpy/visualization/colormaps/cm.py
Labels: visualization, No Changelog Entry Needed, CodeFix, backport 4.0

#6388 Fix the ordering of the API docs
  docs/code_ref/index.rst
  docs/code_ref/sunpy.rst
Labels: DocFix, No Changelog Entry Needed, backport 4.0

#6390 Backport PR #6388 on branch 4.0 (Fix the ordering of the API docs)
  docs/code_ref/index.rst
  docs/code_ref/sunpy.rst
Labels: DocFix, No Changelog Entry Needed, backport 4.0

#6389 Check nddata rather than genericmap in arithmetic compatibility check
  sunpy/util/decorators.py
Labels: No Changelog Entry Needed, CodeFix, No Backport

#6385 Remove tick rotation and grids from timeseries plotting
  changelog/6385.trivial.rst
  docs/whatsnew/4.1.rst
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/timeseries/sources/eve.py
  sunpy/timeseries/sources/lyra.py
  sunpy/timeseries/sources/noaa.py
  sunpy/timeseries/sources/norh.py
  sunpy/timeseries/sources/rhessi.py
Labels: timeseries, CodeFix, No Backport

#6346 PR check list for the dev_guide
  changelog/6346.doc.rst
  docs/dev_guide/contents/pr_checklist.rst
  docs/dev_guide/index.rst
Labels: Documentation, Needs Review, No Backport
