Repository sunpy/sunpy, pull requests merged in 2022-02, with the labels that each got.

#5853 Introduce units of Solar Orbiter/EPD CDF files
  sunpy/io/cdf.py
Labels: BugFix, io, backport 3.1

#5839 Remove GenericTimeSeries_sanitize_units()
  sunpy/timeseries/timeseries_factory.py
  sunpy/timeseries/timeseriesbase.py
Labels: Needs Review, timeseries, No Changelog Entry Needed, No Backport

#5865 Fix scipy deprecation warning
  changelog/5865.doc.rst
  docs/code_ref/known_issues.rst
  setup.cfg
  sunpy/image/coalignment.py
  sunpy/image/tests/test_coalignment.py
  sunpy/image/transform.py
  sunpy/net/tests/test_fido.py
Labels: No Changelog Entry Needed, backport 3.0, backport 3.1

#5878 Misc remote test fixes
  sunpy/database/tests/test_tables.py
  sunpy/net/cdaweb/helpers.py
Labels: Tests, No Changelog Entry Needed, Merge When CI Passes, backport 3.0, backport 3.1

#5872 Add simple GitHub actions script
  .github/workflows/python-test-workflow.yml
  .github/workflows/tests.yml
Labels: No Changelog Entry Needed

#5806 Parse HEK time columns
  changelog/5806.feature.rst
  docs/whatsnew/4.0.rst
  sunpy/net/hek/hek.py
  sunpy/net/hek/tests/test_hek.py
Labels: Needs Review, net, Whats New?, No Backport

#5863 Add TimeSeries test for a URL
  sunpy/timeseries/tests/test_timeseries_factory.py
Labels: Needs Review, No Changelog Entry Needed, No Backport

#5790 Update database __repr__ methods
  changelog/5790.bugfix.rst
  sunpy/database/tables.py
  sunpy/database/tests/test_commands.py
Labels: database, No Backport

#5851 remove pkg_resources
  .test_package_pins.txt
  docs/conf.py
  sunpy/tests/helpers.py
  sunpy/tests/self_test.py
  sunpy/util/sysinfo.py
  sunpy/util/tests/test_sysinfo.py
  tox.ini
Labels: No Changelog Entry Needed, No Backport

#5871 Use map arithmetic in difference image example
  examples/acquiring_data/downloading_cutouts.py
  examples/map/difference_images.py
Labels: DocFix, Examples, No Changelog Entry Needed, No Backport

#5886 Updates HMIMap to check INSTRUME instead of TELESCOP
  changelog/5886.bugfix.rst
  sunpy/map/sources/sdo.py
Labels: map, BugFix, backport 3.0, backport 3.1

#5898 Fix `HMIMap` reference for `build_docs` CI
  changelog/5886.bugfix.rst
Labels: DocFix, No Changelog Entry Needed, No Backport

#5900 Prevent `HEKClient` from parsing time columns with missing values
  sunpy/net/hek/hek.py
Labels: No Changelog Entry Needed, No Backport

#5897 more actions
  .github/workflows/python-test-workflow.yml
  .github/workflows/tests.yml
Labels: No Changelog Entry Needed, CodeFix, Infrastructure, backport 3.0, backport 3.1

#5899 Fix doctest for `get_observatory_groups`
  sunpy/net/cdaweb/helpers.py
Labels: No Changelog Entry Needed, backport 3.1

#5901 [3.1] Backports for CI fixes
  .github/workflows/python-test-workflow.yml
  .github/workflows/tests.yml
  sunpy/net/cdaweb/helpers.py
Labels: No Changelog Entry Needed, CodeFix

#5902 [3.0] Backports for CI fixes
  .github/workflows/python-test-workflow.yml
  .github/workflows/tests.yml
  sunpy/database/tests/test_tables.py
Labels: No Changelog Entry Needed, CodeFix

#5903 added extra branches to actions
  .github/workflows/tests.yml
Labels: No Changelog Entry Needed, CodeFix, No Backport

#5910 Add GH actions oldestdeps workflow
  .github/workflows/tests.yml
Labels: Tests, No Changelog Entry Needed, CodeFix, backport 3.0, backport 3.1

#5911 Use python 3.9 for core tests
  .github/workflows/tests.yml
  setup.cfg
Labels: backport 3.0, backport 3.1

#5906 Pin pytest in oldestdeps tests
  .github/workflows/python-test-workflow.yml
  setup.cfg
  sunpy/image/tests/test_coalignment.py
  tox.ini
Labels: Tests, No Changelog Entry Needed, backport 3.0, backport 3.1

#5921 Fix cdaweb doctest
  sunpy/net/cdaweb/helpers.py
Labels: DocFix, No Changelog Entry Needed, backport 3.0, backport 3.1
