Repository sunpy/sunpy, pull requests merged in 2022-06, with the labels that each got.

#6204 Fix mistake in plotting example
  docs/guide/plotting.rst
Labels: Documentation, DocFix, No Changelog Entry Needed, backport 4.0

#6197 Use STEREO sample data in example gallery
  changelog/6197.doc.rst
  examples/map_transformations/reprojection_aia_euvi_mosaic.py
  examples/map_transformations/reprojection_different_observers.py
  examples/units_and_coordinates/AIA_limb_STEREO.py
  examples/units_and_coordinates/SDO_to_STEREO_Coordinate_Conversion.py
  sunpy/data/_sample.py
Labels: Documentation, DocFix, Examples, backport 4.0

#6206 to_value instead of .value
  docs/guide/plotting.rst
Labels: Documentation, DocFix, No Changelog Entry Needed, backport 4.0

#6211 Add new sample data changelog
  changelog/6197.feature.rst
Labels: backport 4.0

#6196 Improve SRS example annotations
  changelog/6196.doc.rst
  examples/plotting/magnetogram_active_regions.py
Labels: DocFix, Examples, backport 4.0

#6215 Improve GenericMap.save() docstring
  sunpy/map/mapbase.py
Labels: DocFix, No Changelog Entry Needed, backport 4.0

#6217 Overrride EUI waveunit
  sunpy/map/sources/solo.py
Labels: No Changelog Entry Needed, backport 4.0

#6232 Give stale bot write permissions
  .github/workflows/stale_bot.yml
Labels: No Changelog Entry Needed, CodeFix, Infrastructure, Manual Backport

#6235 Example added for GenericMap save method
  sunpy/map/mapbase.py
Labels: Documentation, DocFix, No Changelog Entry Needed, backport 4.0

#6221 updated sample data files
  changelog/6221.breaking.rst
  sunpy/data/_sample.py
Labels: CodeFix, backport 4.0

#6240 Add script to generate github markdown changelog
  tools/generate_github_changelog.py
Labels: No Changelog Entry Needed, CodeFix, Infrastructure, backport 4.0

#6255 Fix FIDO doc tests
  docs/guide/acquiring_data/fido.rst
Labels: DocFix, No Changelog Entry Needed, backport 4.0

#6261 Use conda on RTD to enable control of graphviz version
  .readthedocs.yaml
  .rtd-environment.yml
Labels: DocFix, No Changelog Entry Needed, Infrastructure, backport 4.0

#6256 enqueue_file_kwargs to fix SRS client
  changelog/6256.bugfix.rst
  sunpy/net/dataretriever/client.py
  sunpy/net/dataretriever/sources/noaa.py
Labels: BugFix, net, backport 4.0

#6269 Remove redundant colour definitions
  sunpy/timeseries/sources/eve.py
  sunpy/timeseries/sources/lyra.py
Labels: No Changelog Entry Needed, No Backport

#6271 sphinx_panels -> sphinx_design
  docs/conf.py
  docs/dev_guide/index.rst
  docs/index.rst
  setup.cfg
Labels: DocFix, No Changelog Entry Needed, backport 4.0

#6260 Exposes GOES quality flags
  changelog/6260.feature.rst
  examples/acquiring_data/goes_xrs_example.py
  sunpy/timeseries/sources/goes.py
Labels: timeseries, backport 4.0

#6263 Factor out some common TimeSeries plotting code
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_421_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/timeseries/sources/eve.py
  sunpy/timeseries/sources/fermi_gbm.py
  sunpy/timeseries/sources/goes.py
  sunpy/timeseries/sources/lyra.py
  sunpy/timeseries/sources/noaa.py
  sunpy/timeseries/sources/norh.py
  sunpy/timeseries/sources/rhessi.py
  sunpy/timeseries/timeseriesbase.py
Labels: No Changelog Entry Needed, CodeFix, No Backport

#6242 Use sample data for Venus exapmle
  changelog/6242.feature.rst
  examples/units_and_coordinates/venus_transit.py
  sunpy/data/_sample.py
Labels: DocFix, Examples, data, backport 4.0

#6282 numpy warning changed
  sunpy/map/tests/test_mapbase.py
Labels: Tests, No Changelog Entry Needed, CodeFix, backport 4.0

#6284 Run figure tests with astropy v5.1.0
  .circleci/config.yml
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  tox.ini
Labels: Tests, No Changelog Entry Needed, CodeFix, Infrastructure, backport 4.0

#6289 update sample url for prep of rename of repo url
  changelog/6289.trivial.rst
  sunpy/data/_sample.py
Labels: CodeFix, data, backport 4.0

#6290 basic rhessi tests
  sunpy/map/sources/rhessi.py
  sunpy/map/sources/tests/test_rhessi_source.py
Labels: map, No Changelog Entry Needed, CodeFix, backport 4.0

#6243 Support upcoming parfive 2.0 release
  changelog/6243.trivial.rst
  sunpy/conftest.py
  sunpy/util/parfive_helpers.py
  tox.ini
Labels: net, Merge When CI Passes, backport 4.0

#6288 asdf works on <3.9 CI now
  sunpy/data/test/aiamap_genericmap_1.0.0.asdf
  sunpy/data/test/aiamap_shift_genericmap_1.0.0.asdf
  sunpy/tests/helpers.py
Labels: No Changelog Entry Needed, CodeFix, backport 4.0

#6295 Add support for downloading sample data from more than two mirrors
  changelog/6295.trivial.rst
  sunpy/data/_sample.py
Labels: BugFix, data, backport 4.0

#6302 Fix GOES XRS plotting
  sunpy/timeseries/sources/goes.py
Labels: No Changelog Entry Needed, backport 4.0

#6264 Consistently set x-axis locator/formatter in TimeSeries
  changelog/6264.feature.rst
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/timeseries/sources/eve.py
  sunpy/timeseries/sources/fermi_gbm.py
  sunpy/timeseries/sources/goes.py
  sunpy/timeseries/sources/lyra.py
  sunpy/timeseries/sources/noaa.py
  sunpy/timeseries/sources/norh.py
  sunpy/timeseries/sources/rhessi.py
  sunpy/timeseries/timeseriesbase.py
Labels: timeseries, CodeFix, No Backport

#6285 Change the default scaling for EUI to AsinhStretch
  changelog/6285.bugfix.rst
  sunpy/map/sources/solo.py
Labels: map, BugFix, backport 4.0

#6303 Move timeseries plotting tests to their source test file
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/timeseries/conftest.py
  sunpy/timeseries/sources/tests/test_eve.py
  sunpy/timeseries/sources/tests/test_fermi_gbm.py
  sunpy/timeseries/sources/tests/test_goes.py
  sunpy/timeseries/sources/tests/test_lyra.py
  sunpy/timeseries/sources/tests/test_noaa.py
  sunpy/timeseries/sources/tests/test_norh.py
  sunpy/timeseries/sources/tests/test_rhessi.py
  sunpy/timeseries/tests/test_timeseriesbase.py
Labels: No Changelog Entry Needed, No Backport

#6306 Wrong description in setup.cfg
  setup.cfg
Labels: No Changelog Entry Needed, CodeFix, backport 4.0

#6189 Add function to extract intensity along coord
  changelog/6189.feature.rst
  docs/whatsnew/4.1.rst
  docs/whatsnew/index.rst
  examples/units_and_coordinates/map_slit_extraction.py
  sunpy/map/maputils.py
  sunpy/map/tests/test_maputils.py
Labels: map, Whats New?, No Backport

#6304 De-duplicate some peek methods
  CHANGELOG.rst
  changelog/6304.feature.rst
  changelog/6304.trivial.rst
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/timeseries/sources/goes.py
  sunpy/timeseries/sources/noaa.py
  sunpy/timeseries/sources/rhessi.py
  sunpy/timeseries/timeseriesbase.py
Labels: Refactoring, timeseries, No Backport

#6311 Fixed a bug when working with an observer defined in HEEQ
  changelog/6311.bugfix.rst
  sunpy/coordinates/frameattributes.py
  sunpy/coordinates/tests/test_frameattributes.py
Labels: BugFix, coordinates, backport 4.0
