Repository sunpy/sunpy, pull requests merged in 2023-09, with the labels that each got.

#7183 Make some tweaks for the new sunpy docs theme
  docs/conf.py
  docs/index.rst
  docs/tour.svg
  setup.cfg
Labels: Documentation, Infrastructure, backport 5.0

#7187 Backport PR #7183 on branch 5.0 (Make some tweaks for the new sunpy docs theme)
  docs/conf.py
  docs/index.rst
  docs/tour.svg
  setup.cfg
Labels: Documentation, Infrastructure, backport 5.0

#7188 Prioritize hgln_obs over crln_obs when extracting observer information from FITS headers
  changelog/7188.bugfix.rst
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/coordinates/wcs_utils.py
  sunpy/map/tests/test_mapbase.py
Labels: coordinates, Minor Change, backport 5.0

#7062 Remove binder config
  README.rst
  binder/environment.yml
  changelog/7062.trivial.rst
Labels: Infrastructure, backport 5.0

#7176 Explicitly raise error trying to set LASCOMap.nickname
  sunpy/map/sources/soho.py
  sunpy/map/sources/tests/test_lasco_source.py
Labels: No Changelog Entry Needed, No Backport

#7192 Fix agg warning filter w/ Matplotlib 3.8
  setup.cfg
Labels: No Changelog Entry Needed, backport 5.0

#7194 Backport PR #7188 on branch 5.0 (Prioritize hgln_obs over crln_obs when extracting observer information from FITS headers)
  changelog/7188.bugfix.rst
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/coordinates/wcs_utils.py
  sunpy/map/tests/test_mapbase.py
Labels: coordinates, Minor Change, backport 5.0

#7196 Backport PR #7192 on branch 5.0 (Fix agg warning filter w/ Matplotlib 3.8)
  setup.cfg
Labels: No Changelog Entry Needed, backport 5.0

#7195 Backport PR #7062 on branch 5.0 (Remove binder config)
  README.rst
  binder/environment.yml
  changelog/7062.trivial.rst
Labels: Infrastructure, backport 5.0

#7198 Fix helioveiwer doctest
  docs/topic_guide/helioviewer.rst
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7201 Backport PR #7198 on branch 5.0 (Fix helioveiwer doctest)
  docs/topic_guide/helioviewer.rst
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7199 Fix timseries peak finding example
  changelog/7199.doc.rst
  examples/time_series/timeseries_peak_finding.py
Labels: Examples, Merge When CI Passes, backport 5.0

#7211 Fix statement about orientation of HMI images
  examples/map_transformations/upside_down_hmi.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 5.0

#7212 Backport PR #7211 on branch 5.0 (Fix statement about orientation of HMI images)
  examples/map_transformations/upside_down_hmi.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 5.0

#7197 Fix colormap name in map tutorial
  docs/tutorial/maps.rst
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7213 Backport PR #7197 on branch 5.0 (Fix colormap name in map tutorial)
  docs/tutorial/maps.rst
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 5.0
