Repository sunpy/sunpy, pull requests merged in 2023-08, with the labels that each got.

#7133 Backport PR #7132 on branch 5.0 (Experiment with building a htmlzip of the docs)
  .readthedocs.yaml
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7135 Backport PR #7129 on branch 5.0 (Fix the docbuild?!)
  changelog/7092.bugfix.rst
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7136 Ruff update [skip ci]
  .pre-commit-config.yaml
  examples/time_series/power_spectra_example.py
  sunpy/database/commands.py
  sunpy/database/database.py
  sunpy/database/tables.py
  sunpy/io/_jp2.py
  sunpy/net/dataretriever/client.py
  sunpy/net/scraper.py
  sunpy/net/tests/test_helioviewer.py
  sunpy/tests/mocks.py
  sunpy/tests/tests/test_mocks.py
  sunpy/timeseries/timeseries_factory.py
  sunpy/util/datatype_factory_base.py
  tools/unify_section_headings.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7138 Backport PR #7137 on branch 5.0 (Remove pytest skip in files as it was breaking downstream)
  setup.cfg
  sunpy/io/cdf.py
  sunpy/io/file_tools.py
  sunpy/io/jp2.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7153 Exclude older astropy bugfix releases that are not compatible with matplotlib 3.7
  setup.cfg
Labels: No Changelog Entry Needed, backport 5.0

#7148 Update GBMClient to match different version files
  changelog/7148.bugfix.rst
  sunpy/net/dataretriever/sources/fermi_gbm.py
Labels: net, Minor Change, backport 5.0

#7154 Backport PR #7153 on branch 5.0 (Exclude older astropy bugfix releases that are not compatible with matplotlib 3.7)
  setup.cfg
Labels: No Changelog Entry Needed, backport 5.0

#7155 Backport PR #7148 on branch 5.0 (Update GBMClient to match different version files)
  changelog/7148.bugfix.rst
  sunpy/net/dataretriever/sources/fermi_gbm.py
Labels: net, Minor Change, backport 5.0

#7156 Backport PR #7144 on branch 5.0 (See if increasing min deps helps figure test pass)
  sunpy/tests/figure_hashes_mpl_353_ft_261_astropy_511_animators_100.json
  tox.ini
Labels: No Changelog Entry Needed, Infrastructure, Minor Change, backport 5.0

#7145 removes incorrect block indices from asdf test data
  .pre-commit-config.yaml
  sunpy/data/test/aiamap_genericmap_1.0.0.asdf
  sunpy/data/test/aiamap_shift_genericmap_1.0.0.asdf
Labels: No Changelog Entry Needed, Run cron CI, io/ASDF, Minor Change, backport 5.0

#7157 Backport PR #7145 on branch 5.0 (removes incorrect block indices from asdf test data)
  .pre-commit-config.yaml
  sunpy/data/test/aiamap_genericmap_1.0.0.asdf
  sunpy/data/test/aiamap_shift_genericmap_1.0.0.asdf
Labels: No Changelog Entry Needed, Run cron CI, io/ASDF, Minor Change, backport 5.0

#7134 Typo correction to the frameless example
  examples/map/plot_frameless_image.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7158 Backport PR #7134 on branch 5.0 (Typo correction to the frameless example)
  examples/map/plot_frameless_image.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7143 Create heliographic map header with non-zero longitude for map center
  changelog/7143.feature.rst
  sunpy/map/header_helper.py
  sunpy/map/tests/test_header_helper.py
Labels: coordinates, No Backport

#7167 Backport PR #7163 on branch 5.0 (Catch when the `annotate` keyword for `GenericMap.plot()` is not boolean)
  changelog/7163.trivial.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, Minor Change, backport 5.0

#7165 Add a max pin for opencv in oldesdeps
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7168 Backport PR #7165 on branch 5.0 (Add a max pin for opencv in oldesdeps)
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7164 Bump minimum required Glymur version
  changelog/7164.feature.rst
  setup.cfg
  tox.ini
Labels: Infrastructure, No Backport, Minor Change

#7169 Pin importlib-resources in doc build
  setup.cfg
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7170 Backport PR #7169 on branch 5.0 (Pin importlib-resources in doc build)
  setup.cfg
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7123 Added an example to make an anaglyph 3D stereoscopic image
  changelog/7123.doc.rst
  examples/showcase/stereoscopic_3d.py
Labels: Needs Review, Examples, backport 5.0

#7177 Backport PR #7123 on branch 5.0 (Added an example to make an anaglyph 3D stereoscopic image)
  changelog/7123.doc.rst
  examples/showcase/stereoscopic_3d.py
Labels: Needs Review, Examples, backport 5.0

#7106 Fix bug in get_horizons_coord time dictionary arg
  changelog/7106.bugfix.rst
  sunpy/coordinates/ephemeris.py
  sunpy/coordinates/tests/test_ephemeris.py
Labels: coordinates, Minor Change, backport 5.0

#7181 Backport PR #7106 on branch 5.0 (Fix bug in get_horizons_coord time dictionary arg)
  changelog/7106.bugfix.rst
  sunpy/coordinates/ephemeris.py
  sunpy/coordinates/tests/test_ephemeris.py
Labels: coordinates, Minor Change, backport 5.0
