Repository sunpy/sunpy, pull requests merged in 2023-03, with the labels that each got.

#6811 Updates to the conda environment file
  sunpy-dev-env.yml
Labels: No Changelog Entry Needed, No Backport, Run cron CI

#6813 Unpin towncrier as there's a new release of sphinx-changelog
  setup.cfg
Labels: No Changelog Entry Needed, CodeFix, Infrastructure, backport 4.0, backport 4.1

#6799 Backport PR #6796 on branch 4.0 (fixed mapbase autoalign)
  changelog/6796.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_plotting.py
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: map, BugFix, No Changelog Entry Needed, backport 4.0, backport 4.1

#6800 Backport PR #6796 on branch 4.1 (fixed mapbase autoalign)
  changelog/6796.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_plotting.py
  sunpy/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: map, BugFix, No Changelog Entry Needed, backport 4.0, backport 4.1

#6819 Fix the `extract_along_coords()` docstring for accuracy and clarity
  sunpy/map/maputils.py
Labels: map, DocFix, No Changelog Entry Needed, backport 4.0, backport 4.1

#6821 Backport PR #6819 on branch 4.1 (Fix the `extract_along_coords()` docstring for accuracy and clarity)
  sunpy/map/maputils.py
Labels: map, DocFix, No Changelog Entry Needed, backport 4.1

#6816 Use extract_along_coord in arc example
  examples/plotting/great_arc_example.py
Labels: DocFix, No Changelog Entry Needed, No Backport

#6785 Add guidelines for single approval PRs
  docs/dev_guide/contents/pr_review_procedure.rst
Labels: Documentation, No Changelog Entry Needed, No Backport

#6828 Fix numpy deprecation warnings
  setup.cfg
  sunpy/io/tests/test_ana.py
  sunpy/net/helio/chaincode.py
Labels: No Changelog Entry Needed, Run cron CI, backport 4.0, backport 4.1, Minor Change

#6831 Backport PR #6828 on branch 4.1 (Fix numpy deprecation warnings)
  setup.cfg
  sunpy/io/tests/test_ana.py
  sunpy/net/helio/chaincode.py
Labels: No Changelog Entry Needed, Run cron CI, backport 4.0, backport 4.1, Minor Change

#6830 Backport PR #6828 on branch 4.0 (Fix numpy deprecation warnings)
  setup.cfg
  sunpy/io/tests/test_ana.py
  sunpy/net/helio/chaincode.py
Labels: No Changelog Entry Needed, Run cron CI, backport 4.0, backport 4.1, Minor Change

#6820 make submap() handle both 'BaseCoordinateFrame' and 'SkyCoord'
  changelog/6820.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, backport 4.0, backport 4.1, Minor Change

#6833 Backport PR #6820 on branch 4.0 (make submap() handle both 'BaseCoordinateFrame' and 'SkyCoord')
  changelog/6820.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6834 Backport PR #6820 on branch 4.1 (make submap() handle both 'BaseCoordinateFrame' and 'SkyCoord')
  changelog/6820.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6832 Tweak lon_lat example to have correct lon and lat lines
  examples/plotting/lat_lon_lines.py
Labels: No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6839 Backport PR #6832 on branch 4.1 (Tweak lon_lat example to have correct lon and lat lines)
  examples/plotting/lat_lon_lines.py
Labels: No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6838 Backport PR #6832 on branch 4.0 (Tweak lon_lat example to have correct lon and lat lines)
  examples/plotting/lat_lon_lines.py
Labels: No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6601 Improve performance when fetching data from cdaweb
  sunpy/net/cdaweb/helpers.py
  tools/update_attrs_json.py
Labels: No Changelog Entry Needed, Minor Change

#6846 Update CDAWEB + VSO attrs
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/vso/data/attrs.json
Labels: backport 4.0, backport 4.1, Minor Change

#6847 Backport PR #6846 on branch 4.0 (Update CDAWEB + VSO attrs)
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/vso/data/attrs.json
Labels: backport 4.0, backport 4.1, Minor Change

#6848 Backport PR #6846 on branch 4.1 (Update CDAWEB + VSO attrs)
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/vso/data/attrs.json
Labels: backport 4.0, backport 4.1, Minor Change

#6850 Use new config option to summarise successes in notify action
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Infrastructure, backport 4.0, Minor Change

#6851 Backport PR #6850 on branch 4.0 (Use new config option to summarise successes in notify action)
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Infrastructure, backport 4.0, Minor Change

#6852 Backport PR #6850 on branch 4.1 (Use new config option to summarise successes in notify action)
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Infrastructure, backport 4.0, backport 4.1, Minor Change

#6654 Tox 4.0 and drop tox-conda
  .circleci/config.yml
  .github/workflows/ci.yml
  tox.ini
Labels: No Changelog Entry Needed, Infrastructure, Run cron CI, backport 4.0, backport 4.1, Minor Change

#6856 Update matrix notify action
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Infrastructure, Minor Change

#6639 Tutorialise installation
  changelog/6639.doc.rst
  docs/guide/index.rst
  docs/guide/installation.rst
  docs/index.rst
  docs/intro/index.rst
  docs/intro/installation.rst
Labels: Documentation, Needs Review, No Backport

#6778 Tweak settings for hover
  docs/conf.py
  docs/index.rst
Labels: No Changelog Entry Needed, No Backport

#6871 Rename intro docs folder to tutorial
  .gitignore
  docs/index.rst
  docs/tutorial/acquiring_data/database.rst
  docs/tutorial/acquiring_data/fido.rst
  docs/tutorial/acquiring_data/hek.rst
  docs/tutorial/acquiring_data/helioviewer.rst
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  docs/tutorial/acquiring_data/sample-data.rst
  docs/tutorial/coordinates.rst
  docs/tutorial/index.rst
  docs/tutorial/installation.rst
  docs/tutorial/logger.rst
  docs/tutorial/maps.rst
  docs/tutorial/plotting.rst
  docs/tutorial/time.rst
  docs/tutorial/timeseries.rst
  docs/tutorial/units.rst
Labels: Documentation, No Changelog Entry Needed, No Backport, Minor Change

#6876 Download hvpy files to the sunpy download dir
  examples/units_and_coordinates/STEREO_SECCHI_starfield.py
  examples/units_and_coordinates/getting_lasco_observer_location.py
Labels: Documentation, No Changelog Entry Needed, Minor Change

#6858 Remove un-used fermi gbm code
  sunpy/timeseries/sources/fermi_gbm.py
Labels: timeseries, No Changelog Entry Needed, No Backport, Minor Change

#6855 Adds suggestion in the example autoalign/reproject to use `assume_spherical_screen()`
  changelog/6855.doc.rst
  examples/map_transformations/autoalign_aia_hmi.py
  examples/map_transformations/reprojection_align_aia_hmi.py
Labels: Examples, backport 4.0, backport 4.1, Minor Change

#6878 Backport PR #6855 on branch 4.1 (Adds suggestion in the example autoalign/reproject to use `assume_spherical_screen()`)
  changelog/6855.doc.rst
  examples/map_transformations/autoalign_aia_hmi.py
  examples/map_transformations/reprojection_align_aia_hmi.py
Labels: Examples, backport 4.0, backport 4.1, Minor Change

#6877 Backport PR #6855 on branch 4.0 (Adds suggestion in the example autoalign/reproject to use `assume_spherical_screen()`)
  changelog/6855.doc.rst
  examples/map_transformations/autoalign_aia_hmi.py
  examples/map_transformations/reprojection_align_aia_hmi.py
Labels: Examples, backport 4.0, backport 4.1, Minor Change

#6859 Bump min version of h5netcdf
  changelog/6859.feature.rst
  docs/whatsnew/5.0.rst
  setup.cfg
  sunpy/timeseries/sources/goes.py
  tox.ini
Labels: timeseries, Merge When CI Passes, No Backport

#6874 Moved logger system page from tutorial to guide
  docs/guide/index.rst
  docs/guide/logger.rst
  docs/reference/troubleshooting.rst
  docs/tutorial/index.rst
Labels: No Changelog Entry Needed, Minor Change

#6870 Move the plotting section to map docs
  changelog/6870.doc.rst
  docs/index.rst
  docs/tutorial/index.rst
  docs/tutorial/maps.rst
  docs/tutorial/plotting.rst
Labels: No Backport

#6869 Formally deprecate sunpy.database
  changelog/6869.deprecation.rst
  docs/reference/database.rst
  docs/tutorial/acquiring_data/database.rst
  docs/tutorial/acquiring_data/index.rst
  docs/whatsnew/5.0.rst
  sunpy/database/__init__.py
Labels: No Backport

#6857 Deprecate parsing EVE "averages" files
  changelog/6857.deprecation.rst
  sunpy/timeseries/sources/eve.py
Labels: timeseries, No Backport

#6732 Change use of world_to_pixel / pixel_to_world to wcs.world_to_pixel / pixel_to_world in the docs.
  docs/tutorial/coordinates.rst
  examples/computer_vision_techniques/finding_masking_bright_pixels.py
  examples/map/brightness_pixel_location.py
  examples/plotting/finding_local_peaks_in_solar_data.py
  examples/plotting/hmi_cutout.py
  examples/plotting/plot_rectangle.py
  examples/plotting/xy_lims.py
  sunpy/map/mapbase.py
  sunpy/map/maputils.py
  sunpy/physics/differential_rotation.py
Labels: map, No Changelog Entry Needed, No Backport

#6868 Move Helioviewer migration guide to "Guide" section of docs
  changelog/6868.doc.rst
  docs/guide/helioviewer.rst
  docs/guide/index.rst
  docs/tutorial/acquiring_data/index.rst
Labels: Documentation, No Backport, Minor Change

#6873 Remove sample data page in tutorial
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/sample-data.rst
Labels: No Changelog Entry Needed, No Backport, Minor Change

#6854 Adds query to sort the event type by magnitude
  examples/acquiring_data/querying_the_GOES_event_list.py
Labels: Examples, No Changelog Entry Needed, Merge When CI Passes, Minor Change

#6880 Clean goes xrs tests
  sunpy/timeseries/sources/tests/test_goes.py
Labels: Tests, No Changelog Entry Needed, No Backport, Minor Change

#6825 Made the example Masking HMI based on the intensity values of AIA
  changelog/6825.doc.rst
  examples/map/masking_hmi.py
Labels: Examples, No Backport

#6884 Cut down size of several fetch results to improve speed of online tests
  .gitignore
  docs/tutorial/acquiring_data/fido.rst
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/dataretriever/sources/lyra.py
  sunpy/net/dataretriever/sources/tests/test_lyra_ud.py
  sunpy/net/jsoc/data/attrs.json
  sunpy/net/tests/test_fido.py
  sunpy/net/vso/data/attrs.json
  sunpy/net/vso/table_response.py
Labels: Tests, net, No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6893 [4.0] Backport #6884
  .gitignore
  .pre-commit-config.yaml
  docs/guide/acquiring_data/fido.rst
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/dataretriever/sources/lyra.py
  sunpy/net/dataretriever/sources/tests/test_lyra_ud.py
  sunpy/net/jsoc/data/attrs.json
  sunpy/net/tests/test_fido.py
  sunpy/net/vso/data/attrs.json
  sunpy/net/vso/table_response.py
  sunpy/net/vso/tests/test_vso.py
Labels: No Changelog Entry Needed
