Repository sunpy/sunpy, pull requests merged in 2023-11, with the labels that each got.

#7142 Add a function to calculate the solar eclipse amount for an observer
  changelog/7142.doc.rst
  changelog/7142.feature.1.rst
  changelog/7142.feature.2.rst
  docs/whatsnew/5.1.rst
  examples/showcase/eclipse_amount.py
  sunpy/coordinates/ephemeris.py
  sunpy/coordinates/sun.py
  sunpy/coordinates/tests/conftest.py
  sunpy/coordinates/tests/test_ephemeris.py
  sunpy/coordinates/tests/test_sun.py
Labels: coordinates, Whats New?, No Backport

#7264 Update Fido attrs
  sunpy/net/cdaweb/cdaweb.py
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/jsoc/data/attrs.json
  sunpy/net/vso/data/attrs.json
  sunpy/net/vso/vso.py
Labels: No Changelog Entry Needed

#7237 Add module to use SkyCoord for SPICE computations
  changelog/7237.doc.rst
  changelog/7237.feature.rst
  docs/conf.py
  docs/reference/coordinates/index.rst
  docs/whatsnew/5.1.rst
  examples/units_and_coordinates/spice.py
  setup.cfg
  sunpy-dev-env.yml
  sunpy/coordinates/spice.py
  sunpy/coordinates/tests/test_spice.py
  sunpy/util/tests/test_sysinfo.py
Labels: Needs Review, coordinates, Whats New?, No Backport

#7247 Edit sunpy.io._cdf.read_cdf to avoid Pandas PerformanceWarning: DataFrame is highly fragmented (fix #7246)
  changelog/7247.bugfix.rst
  sunpy/io/_cdf.py
Labels: Needs Review, backport 5.0

#7287 Backport PR #7247 on branch 5.0 (Edit sunpy.io._cdf.read_cdf to avoid Pandas PerformanceWarning: DataFrame is highly fragmented (fix #7246))
  changelog/7247.bugfix.rst
  sunpy/io/_cdf.py
Labels: Needs Review, backport 5.0

#7180 Improve handling of WISPR maps
  changelog/7180.feature.rst
  sunpy/map/sources/psp.py
  sunpy/map/sources/tests/test_wispr_source.py
Labels: Whats New?, No Backport

#7277 Added install page from DKIST
  docs/tutorial/installation.rst
Labels: Documentation, No Changelog Entry Needed, backport 5.0

#7289 Backport PR #7277 on branch 5.0 (Added install page from DKIST)
  docs/tutorial/installation.rst
Labels: Documentation, No Changelog Entry Needed, backport 5.0

#7288 Add missing "What's New" entries
  docs/whatsnew/5.1.rst
Labels: No Changelog Entry Needed

#7269 Update mailmap for 5.1
  .mailmap
Labels: Needs Review, No Changelog Entry Needed, Minor Change

#7270 Update zenodo for 5.1
  .mailmap
  .zenodo.json
Labels: Needs Review, No Changelog Entry Needed

#7290 Release statistics
  .pre-commit-config.yaml
  docs/conf.py
  docs/whatsnew/5.1.rst
Labels: No Changelog Entry Needed, Minor Change

#7291 Remove changelogs for 5.1
  changelog/7018.feature.rst
  changelog/7021.deprecation.rst
  changelog/7062.trivial.rst
  changelog/7068.trivial.rst
  changelog/7092.bugfix.rst
  changelog/7100.trivial.rst
  changelog/7106.bugfix.rst
  changelog/7108.trivial.rst
  changelog/7113.deprecation.rst
  changelog/7114.doc.rst
  changelog/7118.feature.rst
  changelog/7123.doc.rst
  changelog/7142.doc.rst
  changelog/7142.feature.1.rst
  changelog/7142.feature.2.rst
  changelog/7143.feature.rst
  changelog/7148.bugfix.rst
  changelog/7160.doc.rst
  changelog/7163.trivial.rst
  changelog/7164.feature.rst
  changelog/7180.feature.rst
  changelog/7186.feature.rst
  changelog/7188.bugfix.rst
  changelog/7199.doc.rst
  changelog/7200.removal.rst
  changelog/7202.removal.rst
  changelog/7203.removal.rst
  changelog/7206.bugfix.rst
  changelog/7220.feature.rst
  changelog/7237.doc.rst
  changelog/7237.feature.rst
  changelog/7239.feature.rst
  changelog/7240.removal.rst
  changelog/7241.removal.rst
  changelog/7242.removal.rst
  changelog/7247.bugfix.rst
  changelog/7250.removal.rst
  changelog/7261.bugfix.rst
  changelog/7282.trivial.rst
Labels: No Changelog Entry Needed, Minor Change

#7292 fix asdf schema examples
  changelog/7292.trivial.rst
  sunpy/io/special/asdf/resources/schemas/geocentricsolarmagnetospheric-1.0.0.yaml
  sunpy/io/special/asdf/resources/schemas/geomagnetic-1.0.0.yaml
  sunpy/io/special/asdf/resources/schemas/solarmagnetic-1.0.0.yaml
Labels: Minor Change, backport 5.0, backport 5.1

#7297 Backport PR #7292 on branch 5.1 (fix asdf schema examples)
  changelog/7292.trivial.rst
  sunpy/io/special/asdf/resources/schemas/geocentricsolarmagnetospheric-1.0.0.yaml
  sunpy/io/special/asdf/resources/schemas/geomagnetic-1.0.0.yaml
  sunpy/io/special/asdf/resources/schemas/solarmagnetic-1.0.0.yaml
Labels: Minor Change, backport 5.1

#7293 Use sample data for stereoscopic example
  examples/showcase/stereoscopic_3d.py
  sunpy/data/_sample.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.1

#7298 Backport PR #7293 on branch 5.1 (Use sample data for stereoscopic example)
  examples/showcase/stereoscopic_3d.py
  sunpy/data/_sample.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.1

#7302 Tweak to example because of order of operations
  examples/plotting/wcsaxes_plotting_example.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 5.0, backport 5.1

#7304 Backport PR #7302 on branch 5.0 (Tweak to example because of order of operations)
  examples/plotting/wcsaxes_plotting_example.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 5.0, backport 5.1

#7305 Backport PR #7302 on branch 5.1 (Tweak to example because of order of operations)
  examples/plotting/wcsaxes_plotting_example.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 5.0, backport 5.1

#7300 Do not add `pfsspy` GONG map source to registry to avoid `MultipleMatchError`
  docs/whatsnew/5.1.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/gong.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.1

#7306 Backport PR #7300 on branch 5.1 (Do not add `pfsspy` GONG map source to registry to avoid `MultipleMatchError`)
  docs/whatsnew/5.1.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/gong.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.1

#7308 Pin drms to < 0.7
  changelog/7308.trivial.rst
  setup.cfg
Labels: Merge When CI Passes, Minor Change, backport 5.0, backport 5.1

#7309 Backport PR #7308 on branch 5.0 (Pin drms to < 0.7)
  changelog/7308.trivial.rst
  setup.cfg
Labels: Merge When CI Passes, Minor Change, backport 5.0, backport 5.1

#7311 Use v0.6 of drms for intershpinx
  docs/conf.py
Labels: No Changelog Entry Needed, backport 5.0, backport 5.1

#7310 Backport PR #7308 on branch 5.1 (Pin drms to < 0.7)
  changelog/7308.trivial.rst
  setup.cfg
Labels: Merge When CI Passes, Minor Change, backport 5.0, backport 5.1

#7312 Backport PR #7311 on branch 5.1 (Use v0.6 of drms for intershpinx)
  docs/conf.py
Labels: No Changelog Entry Needed, backport 5.0, backport 5.1

#7317 Ad 5.1 changelog to main
  CHANGELOG.rst
  changelog/7292.trivial.rst
  changelog/7308.trivial.rst
Labels: No Changelog Entry Needed, Minor Change

#7318 Add 5.1 to cron jobs
  .github/workflows/scheduled_builds.yml
Labels: No Changelog Entry Needed, Minor Change

#7316 Fixed the superpixel sample
  changelog/7316.doc.rst
  examples/map/map_resampling_and_superpixels.py
Labels: Examples, Minor Change, backport 5.0, backport 5.1

#7321 Backport PR #7316 on branch 5.0 (Fixed the superpixel sample)
  changelog/7316.doc.rst
  examples/map/map_resampling_and_superpixels.py
Labels: Examples, Minor Change, backport 5.0, backport 5.1
