Repository sunpy/sunpy, pull requests merged in 2023-06, with the labels that each got.

#7039 Update paths to ignore for spell checking [skip ci]
  setup.cfg
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7042 Backport PR #7039 on branch 5.0 (Update paths to ignore for spell checking [skip ci])
  setup.cfg
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7041 Backport PR #7040 on branch 5.0 (Added whitespace to doctest block [skip ci])
  docs/dev_guide/contents/logger.rst
  docs/topic_guide/logger.rst
  sunpy/net/cdaweb/cdaweb.py
  sunpy/net/cdaweb/helpers.py
  sunpy/net/dataretriever/sources/eve.py
  sunpy/net/dataretriever/sources/fermi_gbm.py
  sunpy/net/dataretriever/sources/goes.py
  sunpy/net/dataretriever/sources/gong.py
  sunpy/net/dataretriever/sources/lyra.py
  sunpy/net/dataretriever/sources/noaa.py
  sunpy/net/dataretriever/sources/norh.py
  sunpy/net/dataretriever/sources/rhessi.py
  sunpy/net/hek/hek.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7031 Update cdflib to 0.3.20 and update version check for future releases of cdflib
  docs/whatsnew/5.0.rst
  setup.cfg
  sunpy/io/_cdf.py
Labels: No Changelog Entry Needed, Whats New?, Run cron CI, backport 5.0

#7018 enabled passing of corrupt files to map
  changelog/7018.feature.rst
  sunpy/data/test/not_actually_fits.fits
  sunpy/io/tests/test_fits.py
  sunpy/map/map_factory.py
  sunpy/map/tests/test_map_factory.py
Labels: map, No Backport

#7038 Removed diagrams in the docs folder
  docs/diagrams/core_datatypes.dia
  docs/diagrams/map_class_hierarchy.dia
  docs/diagrams/package_layout.dia
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7044 Backport PR #7038 on branch 5.0 (Removed diagrams in the docs folder)
  docs/diagrams/core_datatypes.dia
  docs/diagrams/map_class_hierarchy.dia
  docs/diagrams/package_layout.dia
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7048 Fix tables test
  sunpy/database/tests/test_tables.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7032 Nabil's doc review for 5.0
  CHANGELOG.rst
  docs/how_to/coord_components.rst
  docs/how_to/create_a_map.rst
  docs/how_to/create_coords.rst
  docs/how_to/create_custom_map.rst
  docs/how_to/create_custom_timeseries.rst
  docs/how_to/index.rst
  docs/how_to/parse_time.rst
  docs/how_to/remote_data_manager.rst
  docs/how_to/search_multiple_wavelengths.rst
  docs/how_to/search_vso.rst
  docs/how_to/transform_coords.rst
  docs/index.rst
  docs/reference/coordinates/index.rst
  docs/topic_guide/coordinates/carrington.rst
  docs/topic_guide/coordinates/index.rst
  docs/topic_guide/coordinates/rotatedsunframe.rst
  docs/topic_guide/coordinates/rsun.rst
  docs/topic_guide/coordinates/velocities.rst
  docs/topic_guide/coordinates/wcs.rst
  docs/topic_guide/custom_map_rotate.rst
  docs/topic_guide/extending_fido.rst
  docs/topic_guide/helioviewer.rst
  docs/topic_guide/history_comments.rst
  docs/topic_guide/index.rst
  docs/topic_guide/installation.rst
  docs/topic_guide/logger.rst
  docs/topic_guide/new_map_class.rst
  docs/topic_guide/timeseries_metadata.rst
  docs/tutorial/acquiring_data/hek.rst
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  docs/tutorial/coordinates.rst
  docs/tutorial/index.rst
  docs/tutorial/installation.rst
  docs/tutorial/maps.rst
  docs/tutorial/time.rst
  docs/tutorial/timeseries.rst
  docs/tutorial/units.rst
  docs/whatsnew/0.9.rst
  docs/whatsnew/1.1.rst
  docs/whatsnew/2.0.rst
  docs/whatsnew/2.1.rst
  docs/whatsnew/5.0.rst
  examples/differential_rotation/comparing_rotation_models.py
  examples/differential_rotation/differentially_rotated_coordinate.py
  examples/differential_rotation/differentially_rotated_gridlines.py
  sunpy/coordinates/frames.py
  sunpy/coordinates/metaframes.py
  sunpy/map/sources/mlso.py
  sunpy/net/fido_factory.py
  sunpy/net/jsoc/jsoc.py
Labels: No Changelog Entry Needed, backport 5.0

#7051 Backport PR #7032 on branch 5.0 (Nabil's doc review for 5.0)
  CHANGELOG.rst
  docs/how_to/coord_components.rst
  docs/how_to/create_a_map.rst
  docs/how_to/create_coords.rst
  docs/how_to/create_custom_map.rst
  docs/how_to/create_custom_timeseries.rst
  docs/how_to/index.rst
  docs/how_to/parse_time.rst
  docs/how_to/remote_data_manager.rst
  docs/how_to/search_multiple_wavelengths.rst
  docs/how_to/search_vso.rst
  docs/how_to/transform_coords.rst
  docs/index.rst
  docs/reference/coordinates/index.rst
  docs/topic_guide/coordinates/carrington.rst
  docs/topic_guide/coordinates/index.rst
  docs/topic_guide/coordinates/rotatedsunframe.rst
  docs/topic_guide/coordinates/rsun.rst
  docs/topic_guide/coordinates/velocities.rst
  docs/topic_guide/coordinates/wcs.rst
  docs/topic_guide/custom_map_rotate.rst
  docs/topic_guide/extending_fido.rst
  docs/topic_guide/helioviewer.rst
  docs/topic_guide/history_comments.rst
  docs/topic_guide/index.rst
  docs/topic_guide/installation.rst
  docs/topic_guide/logger.rst
  docs/topic_guide/new_map_class.rst
  docs/topic_guide/timeseries_metadata.rst
  docs/tutorial/acquiring_data/hek.rst
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  docs/tutorial/coordinates.rst
  docs/tutorial/index.rst
  docs/tutorial/installation.rst
  docs/tutorial/maps.rst
  docs/tutorial/time.rst
  docs/tutorial/timeseries.rst
  docs/tutorial/units.rst
  docs/whatsnew/0.9.rst
  docs/whatsnew/1.1.rst
  docs/whatsnew/2.0.rst
  docs/whatsnew/2.1.rst
  docs/whatsnew/5.0.rst
  examples/differential_rotation/comparing_rotation_models.py
  examples/differential_rotation/differentially_rotated_coordinate.py
  examples/differential_rotation/differentially_rotated_gridlines.py
  sunpy/coordinates/frames.py
  sunpy/coordinates/metaframes.py
  sunpy/map/sources/mlso.py
  sunpy/net/fido_factory.py
  sunpy/net/jsoc/jsoc.py
Labels: No Changelog Entry Needed, backport 5.0

#7000 Add topic guide describing ``rsun`` idiosyncracies
  changelog/7000.doc.rst
  docs/topic_guide/index.rst
  docs/topic_guide/rsun.rst
Labels: Documentation, backport 5.0

#7056 Backport PR #7000 on branch 5.0 (Add topic guide describing ``rsun`` idiosyncracies)
  changelog/7000.doc.rst
  docs/topic_guide/index.rst
  docs/topic_guide/rsun.rst
Labels: Documentation, backport 5.0

#7053 Update index url for wheels
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7055 Form more doc rules [ skip ci ]
  docs/dev_guide/contents/documentation.rst
Labels: No Changelog Entry Needed, No Backport, Minor Change

#7054 changelog for anchor updates [ skip ci ]
  changelog/7032.doc.rst
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7058 Backport PR #7054 on branch 5.0 (changelog for anchor updates [ skip ci ])
  changelog/7032.doc.rst
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7061 Add more badges to readme
  README.rst
Labels: No Changelog Entry Needed, No Backport, Minor Change

#7020 Patch broken import for private io modules
  sunpy/io/cdf.py
  sunpy/io/file_tools.py
  sunpy/io/jp2.py
  sunpy/io/tests/test_cdf.py
  sunpy/io/tests/test_filetools.py
  sunpy/io/tests/test_jp2.py
Labels: No Changelog Entry Needed, Merge When CI Passes, Minor Change, backport 5.0

#7063 Backport PR #7020 on branch 5.0 (Patch broken import for private io modules)
  sunpy/io/cdf.py
  sunpy/io/file_tools.py
  sunpy/io/jp2.py
  sunpy/io/tests/test_cdf.py
  sunpy/io/tests/test_filetools.py
  sunpy/io/tests/test_jp2.py
Labels: No Changelog Entry Needed, Merge When CI Passes, Minor Change, backport 5.0

#7065 Backport PR #7064 on branch 5.0 ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7067 Forward port 5.0 changelog
  CHANGELOG.rst
  changelog/7000.doc.rst
  changelog/7032.doc.rst
  changelog/7035.bugfix.rst
Labels: No Changelog Entry Needed, Merge When CI Passes, Minor Change

#7068 Add Dependabot config to autoupdate GitHub action versions
  .github/dependabot.yml
  changelog/7068.trivial.rst
Labels: Infrastructure, Minor Change

#7072 Backport PR #7071 on branch 5.0 ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  setup.cfg
Labels: No Changelog Entry Needed, Minor Change, backport 5.0
