Repository sunpy/sunpy, pull requests merged in 2023-05, with the labels that each got.

#6987 Backport PR #6986 on branch 4.0 (Fix database test)
  sunpy/database/tests/test_tables.py
Labels: No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6988 Backport PR #6986 on branch 4.1 (Fix database test)
  sunpy/database/tests/test_tables.py
Labels: No Changelog Entry Needed, backport 4.0, backport 4.1, Minor Change

#6993 remove section for dev tolls from gallery
  docs/conf.py
  docs/dev_guide/contents/example_gallery.rst
  examples/developer_tools/README.txt
  examples/example_template/example_template.py
Labels: No Changelog Entry Needed, No Backport, Minor Change

#6977 Move map factory examples from reference to a how-to guide
  changelog/6977.doc.rst
  docs/how_to/create_a_map.rst
  docs/how_to/index.rst
  sunpy/map/map_factory.py
Labels: Documentation, No Backport

#6954 Re-organise some coord docs
  changelog/6954.doc.rst
  docs/guide/coordinates/index.rst
  docs/guide/coordinates/rsun.rst
  docs/how_to/coord_components.rst
  docs/how_to/create_coords.rst
  docs/how_to/index.rst
  docs/how_to/transform_coords.rst
  docs/tutorial/coordinates.rst
Labels: Needs Review, No Backport

#6995 Prioritise dateavg over dateobs in wcs_frame_mapping
  changelog/6995.bugfix.rst
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/coordinates/wcs_utils.py
Labels: coordinates, backport 4.0, backport 4.1, Minor Change, backport 5.0

#7001 Backport PR #6995 on branch 4.0 (Prioritise dateavg over dateobs in wcs_frame_mapping)
  changelog/6995.bugfix.rst
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/coordinates/wcs_utils.py
Labels: coordinates, backport 4.0, backport 4.1, Minor Change, backport 5.0

#7002 Backport PR #6995 on branch 4.1 (Prioritise dateavg over dateobs in wcs_frame_mapping)
  changelog/6995.bugfix.rst
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/coordinates/wcs_utils.py
Labels: coordinates, backport 4.0, backport 4.1, Minor Change, backport 5.0

#6991 Replace some TOC headings with raw html to fix sidebar.
  docs/guide/index.rst
  docs/how_to/index.rst
  docs/tutorial/index.rst
Labels: Documentation, No Changelog Entry Needed, Minor Change

#6953 Update zenodo and mailmap for 5.0
  .mailmap
  .zenodo.json
Labels: No Changelog Entry Needed, Minor Change

#7004 Don't assume all rotation matrix keywords are present
  changelog/7004.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, backport 4.0, backport 4.1, backport 5.0

#7007 Backport PR #7004 on branch 4.1 (Don't assume all rotation matrix keywords are present)
  changelog/7004.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, backport 4.0, backport 4.1, backport 5.0

#7006 Backport PR #7004 on branch 4.0 (Don't assume all rotation matrix keywords are present)
  changelog/7004.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/tests/test_mapbase.py
Labels: map, backport 4.0, backport 4.1, backport 5.0

#6853 Change "Reprojecting Images to Different Observers" example to avoid using custom wcs header until necessary
  changelog/6853.doc.rst
  examples/map_transformations/reprojection_different_observers.py
Labels: Documentation, backport 5.0

#6944 Revise Map section of the tutorial
  changelog/6944.doc.rst
  docs/how_to/create_custom_map.rst
  docs/how_to/index.rst
  docs/tutorial/index.rst
  docs/tutorial/maps.rst
  docs/tutorial/timeseries.rst
  examples/showcase/where_is_stereo.py
Labels: Documentation, map, Needs Review

#7008 Final 5.0 bits
  .zenodo.json
  LICENSE.rst
  docs/reference/sunpy_stability.yaml
  docs/whatsnew/5.0.rst
  sunpy/net/cdaweb/data/attrs.json
  sunpy/net/vso/data/attrs.json
Labels: No Changelog Entry Needed, Minor Change

#7012 Backport PR #7011 on branch 5.0 ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7014 Add 5.0 to CRON schedule
  .github/workflows/scheduled_builds.yml
Labels: No Changelog Entry Needed, Infrastructure, Minor Change

#7016 Add cdflib to devdeps
  tox.ini
Labels: No Changelog Entry Needed, Run cron CI, Minor Change, backport 5.0

#7019 Backport PR #7016 on branch 5.0 (Add cdflib to devdeps)
  tox.ini
Labels: No Changelog Entry Needed, Run cron CI, Minor Change, backport 5.0

#7027 Fix online doctest fail
  sunpy/net/cdaweb/helpers.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7025 Patch devdeps for cdflib
  sunpy/io/_cdf.py
Labels: No Changelog Entry Needed, Run cron CI, Minor Change, backport 5.0

#7026 Remove 4.X from cronjobs
  .github/workflows/scheduled_builds.yml
Labels: No Changelog Entry Needed, Infrastructure, Minor Change

#7030 Backport PR #7025 on branch 5.0 (Patch devdeps for cdflib)
  sunpy/io/_cdf.py
Labels: No Changelog Entry Needed, Run cron CI, Minor Change, backport 5.0

#7028 Fix warnings for doc example build
  examples/map_transformations/reprojection_aia_euvi_mosaic.py
  examples/plotting/finegrained_plot.py
  examples/units_and_coordinates/AIA_limb_STEREO.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7033 Backport PR #7028 on branch 5.0 (Fix warnings for doc example build)
  examples/map_transformations/reprojection_aia_euvi_mosaic.py
  examples/plotting/finegrained_plot.py
  examples/units_and_coordinates/AIA_limb_STEREO.py
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7037 Backport PR #7036 on branch 5.0 ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, Minor Change, backport 5.0

#7035 Parse uppercase SRS files
  changelog/7035.bugfix.rst
  docs/reference/io.rst
  sunpy/data/test/SRS/19960106SRS.txt
  sunpy/data/test/SRS/19960430SRS.txt
  sunpy/data/test/SRS/19960513SRS.txt
  sunpy/data/test/SRS/20000922SRS.txt
  sunpy/data/test/SRS/20000927SRS.txt
  sunpy/data/test/SRS/20001001SRS.txt
  sunpy/data/test/SRS/20020624SRS.txt
  sunpy/data/test/SRS/20020628SRS.txt
  sunpy/data/test/SRS/20100621SRS.txt
  sunpy/data/test/SRS/20150101SRS.txt
  sunpy/data/test/SRS/20150306SRS.txt
  sunpy/data/test/SRS/20150906SRS.txt
  sunpy/io/special/srs.py
  sunpy/io/tests/test_srs.py
Labels: io, No Backport
