Repository sunpy/sunpy, pull requests merged in 2024-02, with the labels that each got.

#7429 [5.1] Merge pull request #7417 from nabobalis/pytest
  .github/workflows/ci.yml
  sunpy/database/tests/test_database.py
  sunpy/io/special/asdf/tests/test_coordinate_frames.py
  sunpy/map/tests/test_map_factory.py
  sunpy/map/tests/test_mapbase.py
  sunpy/map/tests/test_mapbase_dask.py
  sunpy/timeseries/sources/tests/test_eve.py
  tox.ini
Labels: No Changelog Entry Needed, Run cron CI

#7428 [5.0] Merge pull request #7417 from nabobalis/pytest
  .github/workflows/ci.yml
  sunpy/database/tests/test_database.py
  sunpy/io/special/asdf/tests/test_coordinate_frames.py
  sunpy/map/tests/test_map_factory.py
  sunpy/map/tests/test_mapbase.py
  sunpy/timeseries/sources/tests/test_eve.py
  tox.ini
Labels: No Changelog Entry Needed

#7431 Remove old webhook config
  .circleci/config.yml
Labels: No Changelog Entry Needed, backport 5.0, backport 5.1

#7433 Backport PR #7431 on branch 5.0 (Remove old webhook config)
  .circleci/config.yml
Labels: No Changelog Entry Needed, backport 5.0, backport 5.1

#7434 Backport PR #7431 on branch 5.1 (Remove old webhook config)
  .circleci/config.yml
Labels: No Changelog Entry Needed, backport 5.0, backport 5.1

#7384 move to pyproject.toml + dedicated tool configs
  .codespellrc
  .coveragerc
  .editorconfig
  .flake8
  .github/workflows/ci.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .readthedocs.yaml
  .ruff.toml
  changelog/7384.trivial.rst
  docs/dev_guide/contents/code_standards.rst
  docs/dev_guide/contents/documentation.rst
  docs/dev_guide/contents/tests.rst
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  sunpy-dev-env.yml
  towncrier.toml
  tox.ini
Labels: No Backport, Run cron CI, Run publish

#7438 Remove two gallery examples that use mpl-animators
  examples/plotting/arrayanimatorwcs.py
  examples/plotting/lineAnimator_examples.py
Labels: Examples, No Backport, Minor Change

#7441 Reduce the tox env_list to the common combinations
  tox.ini
Labels: Infrastructure, Minor Change, backport 5.0, backport 5.1

#7443 Removes internal coordinate-frame docstring code
  sunpy/coordinates/frames.py
Labels: coordinates, No Changelog Entry Needed, No Backport, Minor Change

#7442 update ruff and updated config
  .pre-commit-config.yaml
  .ruff.toml
  sunpy/net/dataretriever/sources/rhessi.py
Labels: Infrastructure, No Backport, Minor Change

#7446 Fix bug which causes Fido.search to crash if SSL verification fails for HelioClient
  changelog/7446.bugfix.rst
  sunpy/net/helio/hec.py
  sunpy/net/helio/tests/test_helio.py
Labels: net, Merge When CI Passes, Minor Change, backport 5.0, backport 5.1

#7448 Backport PR #7446 on branch 5.0 (Fix bug which causes Fido.search to crash if SSL verification fails for HelioClient)
  changelog/7446.bugfix.rst
  sunpy/net/helio/hec.py
  sunpy/net/helio/tests/test_helio.py
Labels: net, Merge When CI Passes, Minor Change, backport 5.0, backport 5.1

#7449 Backport PR #7446 on branch 5.1 (Fix bug which causes Fido.search to crash if SSL verification fails for HelioClient)
  changelog/7446.bugfix.rst
  sunpy/net/helio/hec.py
  sunpy/net/helio/tests/test_helio.py
Labels: net, Merge When CI Passes, Minor Change, backport 5.0, backport 5.1

#7454 Allow units to be passed as strings to header helper
  changelog/7454.feature.rst
  sunpy/map/header_helper.py
  sunpy/map/tests/test_header_helper.py
Labels: map

#7456 Upload to scientific-python-nightly-wheels instead
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, No Backport, Minor Change

#7458 Figure hashes for devdeps
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, Minor Change, backport 5.0, backport 5.1

#7459 Backport PR #7458 on branch 5.0 (Figure hashes for devdeps)
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, Minor Change, backport 5.0, backport 5.1

#7460 Backport PR #7458 on branch 5.1 (Figure hashes for devdeps)
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, Minor Change, backport 5.0, backport 5.1
