Repository sunpy/sunpy, pull requests merged in 2024-10, with the labels that each got.

#7812 Add Angstrom as default unit for HMI wavelength
  changelog/7812.bugfix.rst
  sunpy/map/sources/sdo.py
  sunpy/map/sources/tests/test_hmi_source.py
Labels: map, Minor Change, backport 6.0

#7813 Fix broken conda link in newcomers guide and tidy a little
  changelog/7813.doc.rst
  docs/dev_guide/contents/newcomers.rst
  docs/tutorial/installation.rst
Labels: Documentation, backport 6.0

#7821 Backport PR #7812 on branch 6.0 (Add Angstrom as default unit for HMI wavelength)
  changelog/7812.bugfix.rst
  sunpy/map/sources/sdo.py
  sunpy/map/sources/tests/test_hmi_source.py
Labels: map, Minor Change, backport 6.0

#7822 Backport PR #7813 on branch 6.0 (Fix broken conda link in newcomers guide and tidy a little)
  changelog/7813.doc.rst
  docs/dev_guide/contents/newcomers.rst
  docs/tutorial/installation.rst
Labels: Documentation, backport 6.0

#7830 Update .zenodo.json
  .zenodo.json
Labels: No Changelog Entry Needed, No Backport

#7674 Handle norm for mapsequence
  .github/workflows/ci.yml
  CHANGELOG.rst
  changelog/7674.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/mapsequence.py
  sunpy/map/sources/sdo.py
  sunpy/map/tests/conftest.py
  sunpy/map/tests/test_mapsequence.py
  sunpy/visualization/animator/mapsequenceanimator.py
Labels: map, Minor Change, backport 6.0

#7831 Backport PR #7674 on branch 6.0 (Handle norm for mapsequence)
  .github/workflows/ci.yml
  CHANGELOG.rst
  changelog/7674.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/mapsequence.py
  sunpy/map/sources/sdo.py
  sunpy/map/tests/conftest.py
  sunpy/map/tests/test_mapsequence.py
  sunpy/visualization/animator/mapsequenceanimator.py
Labels: map, Minor Change, backport 6.0

#7832 Backport PR #7829 on branch 6.0 (Updates from the package template)
  .cruft.json
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0

#7834 Fix CI
  docs/topic_guide/coordinates/carrington.rst
  pyproject.toml
  sunpy/coordinates/tests/test_sun.py
  sunpy/io/tests/test_fits.py
  sunpy/net/dataretriever/sources/tests/test_goes_ud.py
  sunpy/net/hek/tests/test_hek.py
Labels: No Changelog Entry Needed, Run cron CI, Minor Change, backport 6.0

#7838 Backport PR #7834 on branch 6.0 (Fix CI)
  docs/topic_guide/coordinates/carrington.rst
  pyproject.toml
  sunpy/coordinates/tests/test_sun.py
  sunpy/io/tests/test_fits.py
  sunpy/net/dataretriever/sources/tests/test_goes_ud.py
  sunpy/net/hek/tests/test_hek.py
Labels: No Changelog Entry Needed, Run cron CI, Minor Change, backport 6.0

#7847 Backport PR #7843 on branch 6.0 (Updates from the package template)
  .cruft.json
  docs/conf.py
  sunpy/_dev/__init__.py
Labels: No Changelog Entry Needed, backport 6.0

#7846 Add support for Python 3.13
  .github/workflows/ci.yml
  pyproject.toml
  sunpy/io/src/ana/_pyana.c
  sunpy/net/fido_factory.py
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 6.0

#7850 Backport PR #7849 on branch 6.0 (Fix figure devdeps)
  sunpy/visualization/wcsaxes_compat.py
Labels: visualization, No Changelog Entry Needed, Minor Change, backport 6.0

#7855 Don't use 3.13 for the core CI yet
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Infrastructure, backport 6.0

#7858 Backport PR #7855 on branch 6.0 (Don't use 3.13 for the core CI yet)
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Infrastructure, backport 6.0

#7854 Use updated astropy.Table api
  changelog/7854.bugfix.rst
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  sunpy/net/attr.py
  sunpy/net/cdaweb/cdaweb.py
Labels: net, Minor Change, backport 6.0

#7859 Backport PR #7854 on branch 6.0 (Use updated astropy.Table api)
  changelog/7854.bugfix.rst
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  sunpy/net/attr.py
  sunpy/net/cdaweb/cdaweb.py
Labels: net, Minor Change, backport 6.0

#7861 Backport PR #7857 on branch 6.0 (Fixed some issues related to WCSAxes in astropy 7.0)
  sunpy/coordinates/frames.py
Labels: map, Minor Change, backport 6.0

#7862 Updates from package template
  .cruft.json
  .github/workflows/sub_package_update.yml
  .pre-commit-config.yaml
  .ruff.toml
  docs/conf.py
  sunpy/_dev/scm_version.py
  sunpy/coordinates/tests/test_wcs_utils.py
  sunpy/map/tests/test_map_factory.py
  sunpy/map/tests/test_mapbase.py
  sunpy/net/dataretriever/sources/tests/test_norh.py
  sunpy/util/tests/test_util.py
  sunpy/visualization/colormaps/tests/test_cm.py
  tools/hek_mkcls.py
Labels: No Changelog Entry Needed, backport 6.0
