Repository sunpy/sunpy, pull requests merged in 2024-11, with the labels that each got.

#7870 Updates from package template
  .cruft.json
  .github/workflows/label_sync.yml
Labels: No Changelog Entry Needed, Infrastructure, No Backport, Minor Change

#7871 Updates from package template
  .cruft.json
  .github/workflows/label_sync.yml
Labels: No Changelog Entry Needed, Infrastructure, No Backport, Minor Change

#7873 Updates from package template
  .cruft.json
  .github/workflows/label_sync.yml
Labels: No Changelog Entry Needed, Infrastructure, No Backport, Minor Change

#7867 Use a fixed time in the past for the gallery example with STEREO locations
  examples/showcase/where_is_stereo.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 6.0

#7876 Backport PR #7867 on branch 6.0 (Use a fixed time in the past for the gallery example with STEREO locations)
  examples/showcase/where_is_stereo.py
Labels: Examples, No Changelog Entry Needed, Minor Change, backport 6.0

#7875 Fix devdeps fails with astropy
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  examples/showcase/where_is_stereo.py
  pytest.ini
  sunpy/net/base_client.py
  sunpy/net/cdaweb/cdaweb.py
  sunpy/net/fido_factory.py
  sunpy/net/hek/tests/test_hek.py
Labels: Tests, No Changelog Entry Needed, Minor Change, backport 6.0

#7877 Backport PR #7875 on branch 6.0 (Fix devdeps fails with astropy)
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  examples/showcase/where_is_stereo.py
  pytest.ini
  sunpy/net/base_client.py
  sunpy/net/cdaweb/cdaweb.py
  sunpy/net/fido_factory.py
  sunpy/net/hek/tests/test_hek.py
Labels: Tests, No Changelog Entry Needed, Minor Change, backport 6.0

#7878 Use main instead of master for figure tests comparison
  pytest.ini
  tox.ini
Labels: No Changelog Entry Needed, Infrastructure, Minor Change, backport 6.0

#7879 Backport PR #7878 on branch 6.0 (Use main instead of master for figure tests comparison )
  pytest.ini
  tox.ini
Labels: No Changelog Entry Needed, Infrastructure, Minor Change, backport 6.0

#7881 Improved clarity & structure of documentation in the installation section; fixed formatting
  docs/tutorial/installation.rst
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, Documentation

#7882 Backport PR #7881 on branch 6.0 (Improved clarity & structure of documentation in the installation section; fixed formatting)
  docs/tutorial/installation.rst
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, Documentation

#7845 Added ability to delay download in data manager
  changelog/7845.feature.rst
  sunpy/data/data_manager/manager.py
  sunpy/data/data_manager/tests/test_manager.py
Labels: Needs Review, data, No Backport

#7887 Only fail docs on deprecation warnings when not on RTD
  docs/conf.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0

#7888 Backport PR #7887 on branch 6.0 (Only fail docs on deprecation warnings when not on RTD)
  docs/conf.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0
