Repository sunpy/sunpy, pull requests merged in 2025-06, with the labels that each got.

#8229 Backport PR #8228 on branch 6.1 (Updates from the package template)
  .cruft.json
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0, backport 6.1, backport 7.0

#8230 Backport PR #8228 on branch 7.0 (Updates from the package template)
  .cruft.json
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0, backport 6.1, backport 7.0

#8231 Add a SUIT plot to whats new
  docs/whatsnew/7.0-suit.png
  docs/whatsnew/7.0.rst
Labels: No Changelog Entry Needed, Minor Change, backport 7.0

#8238 Backport PR #8237 on branch 6.0 (Fix failing CI for pytest 8.4.0 + pytest-xdist + pytest-cov)
  .coveragerc
  sunpy/timeseries/tests/test_timeseries_factory.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1, backport 7.0

#8240 Backport PR #8237 on branch 7.0 (Fix failing CI for pytest 8.4.0 + pytest-xdist + pytest-cov)
  .coveragerc
  sunpy/timeseries/tests/test_timeseries_factory.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1, backport 7.0

#8205 Update Zenodo File for 7.0
  .mailmap
  .zenodo.json
Labels: No Changelog Entry Needed, Minor Change, backport 7.0

#8241 Backport PR #8205 on branch 7.0 (Update Zenodo File for 7.0)
  .mailmap
  .zenodo.json
Labels: No Changelog Entry Needed, Minor Change, backport 7.0

#8236 Fix EIT L0 reference_date fail
  changelog/8236.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/tests/test_eit_source.py
Labels: map, Minor Change, backport 7.0

#8242 Backport PR #8236 on branch 7.0 (Fix EIT L0 reference_date fail)
  changelog/8236.bugfix.rst
  sunpy/map/mapbase.py
  sunpy/map/sources/tests/test_eit_source.py
Labels: map, Minor Change, backport 7.0

#8243 [map_branch] Mergey mergey merge
  .mailmap
  .zenodo.json
  changelog/8236.bugfix.rst
  sunpy/map/mixins/mapmeta.py
  sunpy/map/sources/tests/test_eit_source.py
Labels: No Changelog Entry Needed

#8245 Updates from package template
  .cruft.json
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Run cron CI, Run publish, backport 7.0

#8246 Backport PR #8245 on branch 7.0 (Updates from package template)
  .cruft.json
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Run cron CI, Run publish, backport 7.0

#8251 Fixed numpy 2.3 astropy Time segfault in goes example
  examples/time_series/goes_xrs_nrt_data.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, Bug, backport 6.1, backport 7.0

#8255 Backport PR #8251 on branch 7.0 (Fixed numpy 2.3 astropy Time segfault in goes example)
  examples/time_series/goes_xrs_nrt_data.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, Bug, backport 6.1, backport 7.0

#8256 Backport PR #8249 on branch 7.0 (Update what's new)
  docs/whatsnew/7.0.rst
  pytest.ini
Labels: No Changelog Entry Needed, Minor Change, backport 7.0

#8253 Backport PR #8251 on branch 6.0 (Fixed numpy 2.3 astropy Time segfault in goes example)
  examples/time_series/goes_xrs_nrt_data.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, Bug, backport 6.1, backport 7.0

#8254 Backport PR #8251 on branch 6.1 (Fixed numpy 2.3 astropy Time segfault in goes example)
  examples/time_series/goes_xrs_nrt_data.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, Bug, backport 6.1, backport 7.0

#8258 Removed the vestigial notion that `reproject` is an optional dependency
  sunpy/map/mapbase.py
Labels: map, No Changelog Entry Needed, backport 7.0

#8259 Backport PR #8258 on branch 7.0 (Removed the vestigial notion that `reproject` is an optional dependency)
  sunpy/map/mapbase.py
Labels: map, No Changelog Entry Needed, backport 7.0

#8260 Backport PR #8257 on branch 6.0 (Protected against a bad interaction between astropy's C fast parser of time strings and numpy>=2.3)
  changelog/8257.bugfix.rst
  examples/time_series/goes_xrs_nrt_data.py
  sunpy/time/tests/test_time.py
  sunpy/time/time.py
Labels: time, backport 6.0, backport 6.1, backport 7.0

#8261 Backport PR #8257 on branch 6.1 (Protected against a bad interaction between astropy's C fast parser of time strings and numpy>=2.3)
  changelog/8257.bugfix.rst
  examples/time_series/goes_xrs_nrt_data.py
  sunpy/time/tests/test_time.py
  sunpy/time/time.py
Labels: time, backport 6.0, backport 6.1, backport 7.0

#8262 Backport PR #8257 on branch 7.0 (Protected against a bad interaction between astropy's C fast parser of time strings and numpy>=2.3)
  changelog/8257.bugfix.rst
  examples/time_series/goes_xrs_nrt_data.py
  sunpy/time/tests/test_time.py
  sunpy/time/time.py
Labels: time, backport 6.0, backport 6.1, backport 7.0

#8268 Backport PR #8267 on branch 6.0 (Remove jsoc warning)
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1, backport 7.0

#8271 remove xdist as hard test dep
  pyproject.toml
  pytest.ini
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 7.0

#8272 Backport PR #8271 on branch 7.0 (remove xdist as hard test dep)
  pyproject.toml
  pytest.ini
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 7.0

#8274 [map branch] Rescale header back to original units in wcs setter
  sunpy/map/mapbase.py
Labels: No Changelog Entry Needed

#8282 [map branch] Merge main into map_ndcube_migration
  .cruft.json
  .github/workflows/ci.yml
  CHANGELOG.rst
  changelog/8211.trivial.rst
  changelog/8212.bugfix.rst
  changelog/8236.bugfix.rst
  docs/tutorial/acquiring_data/index.rst
  docs/tutorial/acquiring_data/jsoc.rst
  docs/whatsnew/7.0.rst
  pyproject.toml
  pytest.ini
  sunpy/io/special/asdf/tests/test_time.py
  sunpy/map/mapbase.py
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/time/tests/test_time.py
  sunpy/time/time.py
  tox.ini
Labels: No Changelog Entry Needed

#8283 remove dead branches for weekly builds
  .github/workflows/scheduled_builds.yml
Labels: No Changelog Entry Needed, Infrastructure, No Backport, Minor Change

#8285 Fix double contour method reference
  sunpy/map/mapbase.py
Labels: No Changelog Entry Needed, Minor Change, backport 7.0
