Repository sunpy/sunpy, pull requests merged in 2025-03, with the labels that each got.

#8113 Update the range for B0 angle that is stated in the docstring
  changelog/8113.doc.rst
  sunpy/coordinates/sun.py
Labels: coordinates, Minor Change, backport 6.0, Documentation, backport 6.1

#8114 Backport PR #8113 on branch 6.0 (Update the range for B0 angle that is stated in the docstring)
  changelog/8113.doc.rst
  sunpy/coordinates/sun.py
Labels: coordinates, Minor Change, backport 6.0, Documentation, backport 6.1

#8116 Backport PR #8112 on branch 6.0 (Updates from the package template)
  .cruft.json
  .github/workflows/sub_package_update.yml
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0, backport 6.1

#8117 Backport PR #8112 on branch 6.1 (Updates from the package template)
  .cruft.json
  .github/workflows/sub_package_update.yml
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0, backport 6.1

#8118 Fix typo in 6.1 release notes
  docs/whatsnew/6.1.rst
Labels: No Changelog Entry Needed, Minor Change, Documentation, backport 6.1

#8119 Backport PR #8118 on branch 6.1 (Fix typo in 6.1 release notes)
  docs/whatsnew/6.1.rst
Labels: No Changelog Entry Needed, Minor Change, Documentation, backport 6.1

#8120 Unskip jsoc tests
  output.txt
  sunpy/net/jsoc/tests/test_jsoc.py
  sunpy/net/tests/test_fido.py
  sunpy/net/vso/tests/test_vso.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8121 Backport PR #8120 on branch 6.0 (Unskip jsoc tests)
  output.txt
  sunpy/net/jsoc/tests/test_jsoc.py
  sunpy/net/tests/test_fido.py
  sunpy/net/vso/tests/test_vso.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8122 Backport PR #8120 on branch 6.1 (Unskip jsoc tests)
  output.txt
  sunpy/net/jsoc/tests/test_jsoc.py
  sunpy/net/tests/test_fido.py
  sunpy/net/vso/tests/test_vso.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8123 Remove spurious file
  output.txt
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8124 Backport PR #8123 on branch 6.0 (Remove spurious file)
  output.txt
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8130 Backport PR #8129 on branch 6.0 (Updates from the package template)
  .cruft.json
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0, backport 6.1

#7863 Redesign our scheduled builds
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/notify.yml
  .github/workflows/scheduled_builds.yml
Labels: No Changelog Entry Needed, Run cron CI

#8136 Fix cron again
  .github/workflows/notify.yml
  .github/workflows/scheduled_builds.yml
Labels: No Changelog Entry Needed, Infrastructure, Minor Change

#8140 Fixing url for scraper migration dep warning
  sunpy/net/scraper.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.1

#8145 Backport PR #8142 on branch 6.1 (Updates from the package template)
  .cruft.json
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 6.0, backport 6.1
