Repository sunpy/sunpy, pull requests merged in 2025-04, with the labels that each got.

#8149 Backport PR #8148 on branch 6.1 ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8147 Provide more update to date MPL links in map_editcolormap.py
  examples/plotting/map_editcolormap.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8126 Allow non-FITS-standard units on HMI map
  changelog/8126.bugfix.rst
  sunpy/map/sources/sdo.py
  sunpy/map/sources/tests/test_hmi_source.py
Labels: map, No Backport, Source Metadata

#7971 Adds SUITMap subclass to the Generic Map and implements custom colorscheme for each filters.
  changelog/7971.feature.rst
  sunpy/data/test/SUT_T24_0847_000444_Lev1.0_2024-06-28T18.21.33.178_0971NB03.header
  sunpy/map/sources/__init__.py
  sunpy/map/sources/suit.py
  sunpy/map/sources/tests/test_suit_source.py
  sunpy/tests/figure_hashes_mpl_382_ft_261_astropy_600_animators_111.json
  sunpy/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  sunpy/visualization/colormaps/cm.py
  sunpy/visualization/colormaps/color_tables.py
  sunpy/visualization/colormaps/data/suit_bb01.csv
  sunpy/visualization/colormaps/data/suit_bb02.csv
  sunpy/visualization/colormaps/data/suit_bb03.csv
  sunpy/visualization/colormaps/data/suit_nb01.csv
  sunpy/visualization/colormaps/data/suit_nb02.csv
  sunpy/visualization/colormaps/data/suit_nb03.csv
  sunpy/visualization/colormaps/data/suit_nb04.csv
  sunpy/visualization/colormaps/data/suit_nb05.csv
  sunpy/visualization/colormaps/data/suit_nb06.csv
  sunpy/visualization/colormaps/data/suit_nb07.csv
  sunpy/visualization/colormaps/data/suit_nb08.csv
Labels: map, Whats New?, No Backport

#8106 Deprecate util.net.donwload_file and download_fileobj
  changelog/8106.deprecation.rst
  docs/dev_guide/contents/newcomers.rst
  sunpy/util/net.py
Labels: Needs Review, util, No Backport

#8157 Backport PR #8154 on branch 6.1 (Remove use of deprecated astropy isiterable)
  sunpy/net/attr.py
  sunpy/net/jsoc/jsoc.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1

#8156 Backport PR #8154 on branch 6.0 (Remove use of deprecated astropy isiterable)
  sunpy/net/attr.py
  sunpy/net/jsoc/jsoc.py
Labels: No Changelog Entry Needed, Minor Change, backport 6.0, backport 6.1
